/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_seguro_vehiculos;

import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class frmModelos extends javax.swing.JInternalFrame {

    public static frmModelos getInstancia() {

        if (instancia == null || instancia.isClosed) {
            instancia = new frmModelos();
        }
        return instancia;
    }
    
    
    
    private frmModelos() {
        
        modelo=new DefaultTableModel(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        initComponents();
        
        //Devuelvo la conexion de Principal
        conexion=frmPrincipal.devConexion();
        
        //Relleno las maras
        conexion.rellenaComboBox2Columnas(cmbMarca, 
                                        CONSULTAMARCA,
                                        "--Elige Marca--", 
                                        "idmarca",
                                        "marca");
        
        ButtonGroup grupo=new ButtonGroup();
        
        grupo.add(rdbEliminado);
        grupo.add(rdbNoEliminado);
        
        rdbNoEliminado.setSelected(true);
        
        MetodosComunes.bordeConTitulo(jPanel1, "Filtro");
        
        MetodosComunes.bordeConTitulo(jPanel2, "Informacion");
        
        rellenaModelos(CONSULTAMODELOS+devolverEstado());
        
    }

    
    private void rellenaModelos(String consulta){
        
        conexion.ejecutarConsulta(consulta);
        
        MetodosComunes.limpiarTabla(modelo);
        
        conexion.rellenaJTableBD(modelo);
        
        //Oculto el id de modelo
        MetodosComunes.ocultarColumnaJTable(jTable1, 0);
        
        //Centro los datos y cabecera
        MetodosComunes.centraCabecera(jTable1);
        MetodosComunes.centrarDatos(jTable1);
        
       
        
        conexion.cerrarResult();
        conexion.cerrarSentencia();
        
    }
    
    //Indica si mostrar eliminados o no eliminados
    private String devolverEstado(){
        
        if (rdbEliminado.isSelected()){
            return ELIMINADO;
        }else{
            return NOELIMINADO;
        }
        
    }
    
    //Indica que mara devuelve (si hay alguna seleccionada)
    private String devolverMarca(){
        
        String condicion="";

        if(MetodosComunes.devolverCodigoComboBox(cmbMarca)!=-1){
            condicion+=" and ma.idmarca="+MetodosComunes.devolverCodigoComboBox(cmbMarca)+"";
        }
        
        return condicion;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiarFiltro = new javax.swing.JButton();
        cmbMarca = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdbEliminado = new javax.swing.JRadioButton();
        rdbNoEliminado = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modelos");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimpiarFiltro.setText("Limpiar");
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltroActionPerformed(evt);
            }
        });

        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });

        jLabel1.setText("Marca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(219, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpiarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(btnLimpiarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(modelo);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        rdbEliminado.setText("Eliminado");
        rdbEliminado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbEliminadoItemStateChanged(evt);
            }
        });

        rdbNoEliminado.setText("No eliminado");
        rdbNoEliminado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbNoEliminadoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbNoEliminado)
                    .addComponent(rdbEliminado))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbEliminado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNoEliminado)
                        .addGap(49, 49, 49)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
        if (jTable1.getRowCount()==0){
            
            JOptionPane.showMessageDialog(this, "No hay registros que modificar");
        
        }else{
        
            int fila=jTable1.getSelectedRow();

            if(fila!=-1){
                
                BigDecimal idModelo=(BigDecimal)jTable1.getValueAt(fila, 0);    
                
                InformacionModelo ventana=new InformacionModelo(idModelo.intValue());
        
                ventana.setVisible(true);
                
                rellenaModelos(CONSULTAMODELOS+devolverEstado()+devolverMarca());
                
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      
        InformacionModelo ventana=new InformacionModelo();
        
        ventana.setVisible(true);
        
        rellenaModelos(CONSULTAMODELOS+devolverEstado()+devolverMarca());
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        if (jTable1.getRowCount()==0){
            
            JOptionPane.showMessageDialog(this, "No hay registros que eliminar");
        
        }else{
        
            int fila=jTable1.getSelectedRow();

            if(fila!=-1){

                BigDecimal idModelo=(BigDecimal)jTable1.getValueAt(fila, 0);
                
                String sql="select count(*) "
                        + "from s_vehiculos "
                        + "where eliminado=0 "
                        + "and "
                        + "idmodelo="+idModelo.intValue();
                
                //Compruebo que puedo borrar sin problemas (no hay modelos activos en vehiculos)
                if (!conexion.consultaVaciaV2(sql)){
                    
                    JOptionPane.showMessageDialog(this, 
                                                "No se puede eliminar el modelo, existen modelos en vehiculos.", 
                                                "Error", 
                                                JOptionPane.ERROR_MESSAGE);
                    
                }else{
                    
                    int seleccion=JOptionPane.showConfirmDialog(this, 
                                                            "¿Estas seguro de que quieres eliminar el registro?", 
                                                            "Confirmacion", 
                                                            JOptionPane.YES_NO_OPTION);
            
                    if(seleccion==JOptionPane.YES_OPTION){

                        //Actualizamos eliminado
                        conexion.ejecutarInstruccion("update s_modelos "
                                                        + "set eliminado=1"
                                                        + "where idModelo="+idModelo);

                        conexion.commit();
                        
                        //Confirmacion
                        JOptionPane.showMessageDialog(this, 
                                                    "Modelo eliminado", 
                                                    "Exito", 
                                                    JOptionPane.INFORMATION_MESSAGE);

                    }

                }

                rellenaModelos(CONSULTAMODELOS+devolverEstado()+devolverMarca());
                
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        rellenaModelos(CONSULTAMODELOS+devolverMarca()+devolverEstado());
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimpiarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltroActionPerformed

        cmbMarca.setSelectedIndex(0);
        
        rellenaModelos(CONSULTAMODELOS+devolverEstado());
        
    }//GEN-LAST:event_btnLimpiarFiltroActionPerformed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void rdbNoEliminadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbNoEliminadoItemStateChanged

    }//GEN-LAST:event_rdbNoEliminadoItemStateChanged

    private void rdbEliminadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbEliminadoItemStateChanged
       
        //Al pulsar en Eliminado o no eliminado, se rellenan sus respectivos datos
        
        if (ItemEvent.SELECTED==evt.getStateChange()){
            
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            
            rellenaModelos(CONSULTAMODELOS+ELIMINADO+devolverMarca());
            
        }else{
            
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
            
            rellenaModelos(CONSULTAMODELOS+NOELIMINADO+devolverMarca());
            
        }
        
        
    }//GEN-LAST:event_rdbEliminadoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiarFiltro;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbEliminado;
    private javax.swing.JRadioButton rdbNoEliminado;
    // End of variables declaration//GEN-END:variables
    private ConexionDB conexion;
    private DefaultTableModel modelo;
    private static frmModelos instancia;
    
    //Constantes
    private final String CONSULTAMODELOS="select mo.idmodelo,mo.modelo, ma.marca "
                                        + "from s_modelos mo, s_marcas ma "
                                        + "where ma.idmarca=mo.idmarca ";
    private final String CONSULTAMARCA="select idmarca, marca "
                                        + "from s_marcas "
                                        + "where eliminado=0";
    private final String ELIMINADO="and mo.eliminado=1";
    private final String NOELIMINADO="and mo.eliminado=0";
}
