/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_seguro_vehiculos;

import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class frmMarcas extends javax.swing.JInternalFrame {

    
    public static frmMarcas getInstancia() {

        if (instancia == null || instancia.isClosed) {
            instancia = new frmMarcas();
        }
        return instancia;
    }
    
    
    private frmMarcas() {
       
        modelo=new DefaultTableModel(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        initComponents();
        
        //Devuelvo la conexion de principal
        conexion=frmPrincipal.devConexion();
        
        ButtonGroup grupo=new ButtonGroup();
        
        grupo.add(rdbEliminado);
        grupo.add(rdbNoEliminado);
        
        rdbNoEliminado.setSelected(true);
        
        MetodosComunes.bordeConTitulo(jPanel1, "Filtro");
        
        MetodosComunes.bordeConTitulo(jPanel2, "Informacion");
        
        rellenaMarcas(CONSULTAMARCAS+NOELIMINADO+devolverFiltro());
        
        //Evitamos que peguen texto en la descripcion de la marca
        MetodosComunes.evitarPegar(txtDescripcion);
        
    }

    private void rellenaMarcas(String consulta){
        
        conexion.ejecutarConsulta(consulta);
        
        MetodosComunes.limpiarTabla(modelo);
        
        conexion.rellenaJTableBD(modelo);
        
        //Ocultamos el id y centramos la cabecera y los datos
        MetodosComunes.ocultarColumnaJTable(jTable1, 0);
        MetodosComunes.centraCabecera(jTable1);
        MetodosComunes.centrarDatos(jTable1);
        
       
        
        conexion.cerrarResult();
        conexion.cerrarSentencia();
        
    }
    
    //Indica si mostrar eliminados o no eliminados
    private String devolverEstado(){
        
        if (rdbEliminado.isSelected()){
            return ELIMINADO;
        }else{
            return NOELIMINADO;
        }
        
        
    }
    
    //Obtiene los datos del filtro (si se ha escrito algo)
    private String devolverFiltro(){
        
        String condicion="";
        
        if(!txtDescripcion.getText().equals("")){
           condicion+=" and trim(upper(marca)) like '%"+txtDescripcion.getText().toUpperCase().trim()+"%'";
        }
        
        return condicion;
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        lblControlFiltroDescripcion = new javax.swing.JLabel();
        btnLimpiarFiltro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdbEliminado = new javax.swing.JRadioButton();
        rdbNoEliminado = new javax.swing.JRadioButton();
        Informe = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Marcas");

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre marca");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimpiarFiltro.setText("Limpiar");
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblControlFiltroDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblControlFiltroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnLimpiarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(modelo);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        rdbEliminado.setText("Eliminado");
        rdbEliminado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbEliminadoItemStateChanged(evt);
            }
        });
        rdbEliminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEliminadoActionPerformed(evt);
            }
        });

        rdbNoEliminado.setText("No eliminado");

        Informe.setText("Informe");
        Informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbNoEliminado)
                    .addComponent(rdbEliminado)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(Informe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(rdbEliminado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNoEliminado)
                        .addGap(43, 43, 43)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Informe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

         if (jTable1.getRowCount()==0){
            
            JOptionPane.showMessageDialog(this, "No hay registros que modificar");
        
        }else{
        
            int fila=jTable1.getSelectedRow();

            if(fila!=-1){
                

                BigDecimal idMarca=(BigDecimal)jTable1.getValueAt(fila, 0);    
                
                InformacionMarca ventana=new InformacionMarca(idMarca.intValue());
        
                ventana.setVisible(true);
                
                rellenaMarcas(CONSULTAMARCAS+devolverEstado());
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        }
        
         
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       
        InformacionMarca ventana=new InformacionMarca();
        
        ventana.setVisible(true);
        
        rellenaMarcas(CONSULTAMARCAS+devolverEstado()+devolverFiltro());
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        if (jTable1.getRowCount()==0){
            
            JOptionPane.showMessageDialog(this, "No hay registros que eliminar");
        
        }else{
        
            int fila=jTable1.getSelectedRow();

            if(fila!=-1){

                BigDecimal idMarca=(BigDecimal)jTable1.getValueAt(fila, 0);
                    
                String sql="select count(*) "
                        + "from s_vehiculos v, s_modelos m "
                        + "where v.idmodelo=m.idmodelo and v.eliminado=0 "
                        + "and "
                        + "m.idmarca in (select idmarca "
                                        + "from s_marcas "
                                        + "where idmarca="+idMarca.intValue()+" "
                                        + "and "
                                        + "eliminado=0)";
                
                //Compruebo que la marca no esta siendo ya utilizada en vehiculos.
                if (!conexion.consultaVaciaV2(sql)){
                    
                    JOptionPane.showMessageDialog(this, 
                                                "No se puede eliminar la marca, existen marcas en vehiculos.", 
                                                "Error", 
                                                JOptionPane.ERROR_MESSAGE);
                    
                }else{
                
                    int seleccion=JOptionPane.showConfirmDialog(this, 
                                                                "¿Estas seguro de que quieres eliminar el registro?", 
                                                                "Confirmacion", 
                                                                JOptionPane.YES_NO_OPTION);

                    if(seleccion==JOptionPane.YES_OPTION){

                        //Actualizamos eliminado
                        conexion.ejecutarInstruccion("update s_marcas "
                                                        + "set eliminado=1"
                                                        + "where idMarca="+idMarca);

                        conexion.commit();

                        JOptionPane.showMessageDialog(this, 
                                                    "Marca eliminada", 
                                                    "Exito", 
                                                    JOptionPane.INFORMATION_MESSAGE);


                    }

                
                }
                
                rellenaMarcas(CONSULTAMARCAS+devolverEstado()+devolverFiltro());
                
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
       
        rellenaMarcas(CONSULTAMARCAS+devolverEstado()+devolverFiltro());
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        
        MetodosComunes.escribirSoloLetrasYEspacios(evt, lblControlFiltroDescripcion);
        
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void btnLimpiarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltroActionPerformed
        
        txtDescripcion.setText("");
        
        rellenaMarcas(CONSULTAMARCAS+devolverEstado());
        
    }//GEN-LAST:event_btnLimpiarFiltroActionPerformed

    private void rdbEliminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEliminadoActionPerformed
       
    }//GEN-LAST:event_rdbEliminadoActionPerformed

    private void rdbEliminadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbEliminadoItemStateChanged
       if (ItemEvent.SELECTED==evt.getStateChange()){
            
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            
            rellenaMarcas(CONSULTAMARCAS+ELIMINADO+devolverFiltro());
            
        }else{
            
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
            
            rellenaMarcas(CONSULTAMARCAS+NOELIMINADO+devolverFiltro());
            
        }
    }//GEN-LAST:event_rdbEliminadoItemStateChanged

    private void InformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeActionPerformed
       
        InformeConectores informe = new InformeConectores("listadoMarcas", conexion);
        informe.crearInforme(null);
        
    }//GEN-LAST:event_InformeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Informe;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiarFiltro;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblControlFiltroDescripcion;
    private javax.swing.JRadioButton rdbEliminado;
    private javax.swing.JRadioButton rdbNoEliminado;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
    private ConexionDB conexion;
    private DefaultTableModel modelo;
    private static frmMarcas instancia;
    
    //Constantes
    private final String CONSULTAMARCAS="select idmarca, marca from s_marcas ";
    private final String ELIMINADO="where eliminado=1";
    private final String NOELIMINADO="where eliminado=0";
    
}
