/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_seguro_vehiculos;

import javax.swing.JDesktopPane;

/**
 *
 * @author Alumno
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        
        this.setTitle("Gestion de seguros de vehiculos");
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        initComponents();
        
        //Conexion usada en toda la aplicacion
        conexion=new ConexionDB("Oracle", "LOCALHOST", "ad", "ad", "ORADAM2");
        
    }

    //DEvuelve la conexion a cualquier frame
    public static ConexionDB devConexion(){
        return conexion;
    }
    
    public static JDesktopPane devPrincipal(){
        return principal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuVehiculos = new javax.swing.JMenu();
        menuIMarcas = new javax.swing.JMenuItem();
        menuIModelos = new javax.swing.JMenuItem();
        menuIVehiculos = new javax.swing.JMenuItem();
        menuAccidentes = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        menuClientes.setText("Gestion Clientes");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuClientes.add(jMenuItem2);

        jMenuBar1.add(menuClientes);

        menuVehiculos.setText("Gestion Vehiculos");

        menuIMarcas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuIMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas.png"))); // NOI18N
        menuIMarcas.setText("Marcas");
        menuIMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIMarcasActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIMarcas);

        menuIModelos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuIModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modelos.png"))); // NOI18N
        menuIModelos.setText("Modelos");
        menuIModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIModelosActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIModelos);

        menuIVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuIVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehiculo.png"))); // NOI18N
        menuIVehiculos.setText("Vehiculos");
        menuIVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIVehiculosActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuIVehiculos);

        jMenuBar1.add(menuVehiculos);

        menuAccidentes.setText("Gestion Accidentes");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parte.png"))); // NOI18N
        jMenuItem6.setText("Partes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuAccidentes.add(jMenuItem6);

        jMenuBar1.add(menuAccidentes);

        menuSalir.setText("Salir de la aplicacion");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        jMenuItem8.setText("Salir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuSalir.add(jMenuItem8);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        principal.removeAll();
        
        principal.updateUI();
        
        frmClientes ventana=frmClientes.getInstancia();
        
        principal.add(ventana);
        
        ventana.show();
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuIVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIVehiculosActionPerformed
        
        principal.removeAll();
        
        principal.updateUI();
        
        frmVehiculos ventana=frmVehiculos.getInstancia();
        
        principal.add(ventana);
        
        ventana.show();
        
    }//GEN-LAST:event_menuIVehiculosActionPerformed

    private void menuIModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIModelosActionPerformed
        
        principal.removeAll();
        
        principal.updateUI();
        
        frmModelos ventana=frmModelos.getInstancia();
        
        principal.add(ventana);
        
        ventana.show();
        
    }//GEN-LAST:event_menuIModelosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        //Cierro la conexion
        if (conexion!=null){
            
            conexion.cerrarConexion();
            
        }
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuIMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIMarcasActionPerformed
        
        principal.removeAll();
        
        principal.updateUI();
        
        frmMarcas ventana=frmMarcas.getInstancia();
        
        principal.add(ventana);
        
        ventana.show();
        
    }//GEN-LAST:event_menuIMarcasActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        principal.removeAll();
        
        principal.updateUI();
        
        frmPartes ventana=frmPartes.getInstancia();
        
        principal.add(ventana);
        
        ventana.show();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
        //Cierro la conexion
        if (conexion!=null){
            
            conexion.cerrarConexion();
            
        }
        
        System.exit(0);
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu menuAccidentes;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuIMarcas;
    private javax.swing.JMenuItem menuIModelos;
    private javax.swing.JMenuItem menuIVehiculos;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuVehiculos;
    private static javax.swing.JDesktopPane principal;
    // End of variables declaration//GEN-END:variables
    private static ConexionDB conexion;
    
    //Constantes usadas en todos los frames, para saber que operacion se realiza
    public static final int INSERT=1;
    public static final int UPDATE=2;
    
}
