/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_seguro_vehiculos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class InformacionSubParte extends javax.swing.JDialog {

    /**
     * Creates new form InformacionSubParte
     */
    public InformacionSubParte(int idParte) {
        
        this.setModal(true);
        
        initComponents();
        
        conexion=frmPrincipal.devConexion();
        
        codigoOperacion=frmPrincipal.INSERT;
        
        idParteActual= idParte;
        
        MetodosComunes.rellenaComboBox(cmbTipo, frmPartes.TIPOS);
        
        MetodosComunes.evitarPegar(txtCoste);
        
    }
    
    public InformacionSubParte(int idParte, int idSubParte) {
        
        this.setModal(true);
        
        initComponents();
        
        MetodosComunes.rellenaComboBox(cmbTipo, frmPartes.TIPOS);
        
        conexion=frmPrincipal.devConexion();
     
        codigoOperacion=frmPrincipal.UPDATE;
        
        idSubParteActual=idSubParte;
        
        idParteActual=idParte;
        
        rellenaDatos(idSubParte);
        
        MetodosComunes.evitarPegar(txtCoste);
        
    }
    
    private void rellenaDatos(int idSubParte){
    
        conexion.ejecutarConsulta("select * from s_subpartes where idSubparte="+idSubParte);
        
        ResultSet aux=conexion.getResultSet();
        
        try {
        
            aux.next();
        
            String tipo=aux.getString("tipo");
            
            if(tipo.equals("P")){
                cmbTipo.setSelectedIndex(1);
            }else{
                cmbTipo.setSelectedIndex(2);
            }
            
            txtAreaDescripcion.setText(aux.getString("descrip"));
            
            txtCoste.setText(String.valueOf(aux.getDouble("coste")));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(InformacionSubParte.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        txtCoste = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblControlCoste = new javax.swing.JLabel();
        lblControlDescripcion = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion subparte");
        setResizable(false);

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setWrapStyleWord(true);
        txtAreaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaDescripcion);

        txtCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCosteKeyTyped(evt);
            }
        });

        jLabel1.setText("Tipo");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Coste");

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblControlCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblControlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addComponent(lblControlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblControlCoste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGrabar))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        String error="";

        if(cmbTipo.getSelectedIndex()==0){
            error+="- Indica el tipo\n";
        }

        if(txtCoste.getText().isEmpty()){
            error+="- Escribe un coste\n";
        }

        //Si no hay errores, la operacion se puede completar
        if(error.equals("")){

            //Sacamos algunos datos necesarios

            char tipo=cmbTipo.getSelectedItem().toString().charAt(0);

            //Depende del codigo de operacion, haremos una operacion u otra
            if (codigoOperacion==frmPrincipal.INSERT){

                idSubParteActual=conexion.proximoIDDisponible("idsubparte", "s_subpartes");

                conexion.ejecutarInstruccion("insert into s_subpartes values("
                    + idSubParteActual + ", "
                    + "'"+tipo+"', "
                    + "'"+txtAreaDescripcion.getText()+"', "
                    + txtCoste.getText()+", "
                    + idParteActual+ ", "
                    + "0)");
                
                JOptionPane.showMessageDialog(this, "Subparte añadida");

            }else{

                conexion.ejecutarInstruccion("update s_subpartes "
                    + "set tipo='" + tipo + "', "
                    + "descrip='"+txtAreaDescripcion.getText()+ "', "
                    + "coste="+txtCoste.getText()
                    + " where idsubparte="+idSubParteActual);

                JOptionPane.showMessageDialog(this, "Subparte actualizada");
            }

            conexion.commit();
            
            this.setVisible(false);

        }else{
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCosteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCosteKeyTyped
        MetodosComunes.escribirSoloDoubles(txtCoste, evt, lblControlCoste, 2);
    }//GEN-LAST:event_txtCosteKeyTyped

    private void txtAreaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaDescripcionKeyTyped
        
        MetodosComunes.noEscribirMasDe(txtAreaDescripcion, 100, evt, lblControlDescripcion);
        
    }//GEN-LAST:event_txtAreaDescripcionKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblControlCoste;
    private javax.swing.JLabel lblControlDescripcion;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtCoste;
    // End of variables declaration//GEN-END:variables
    private ConexionDB conexion;
    private int codigoOperacion;
    private int idSubParteActual;
    private int idParteActual;
}
