package modelo;
// Generated 09-ene-2015 13:35:19 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PcodPobl generated by hbm2java
 */
public class PcodPobl  implements java.io.Serializable {


     private BigDecimal idcodPobl;
     private Pcodigopostales pcodigopostales;
     private Ppoblaciones ppoblaciones;
     private Pprovincias pprovincias;
     private Set beditorialeses = new HashSet(0);

    public PcodPobl() {
    }

	
    public PcodPobl(BigDecimal idcodPobl) {
        this.idcodPobl = idcodPobl;
    }
    public PcodPobl(BigDecimal idcodPobl, Pcodigopostales pcodigopostales, Ppoblaciones ppoblaciones, Pprovincias pprovincias, Set beditorialeses) {
       this.idcodPobl = idcodPobl;
       this.pcodigopostales = pcodigopostales;
       this.ppoblaciones = ppoblaciones;
       this.pprovincias = pprovincias;
       this.beditorialeses = beditorialeses;
    }
   
    public BigDecimal getIdcodPobl() {
        return this.idcodPobl;
    }
    
    public void setIdcodPobl(BigDecimal idcodPobl) {
        this.idcodPobl = idcodPobl;
    }
    public Pcodigopostales getPcodigopostales() {
        return this.pcodigopostales;
    }
    
    public void setPcodigopostales(Pcodigopostales pcodigopostales) {
        this.pcodigopostales = pcodigopostales;
    }
    public Ppoblaciones getPpoblaciones() {
        return this.ppoblaciones;
    }
    
    public void setPpoblaciones(Ppoblaciones ppoblaciones) {
        this.ppoblaciones = ppoblaciones;
    }
    public Pprovincias getPprovincias() {
        return this.pprovincias;
    }
    
    public void setPprovincias(Pprovincias pprovincias) {
        this.pprovincias = pprovincias;
    }
    public Set getBeditorialeses() {
        return this.beditorialeses;
    }
    
    public void setBeditorialeses(Set beditorialeses) {
        this.beditorialeses = beditorialeses;
    }




}


