package modelo;
// Generated 09-ene-2015 13:35:19 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pprovincias generated by hbm2java
 */
public class Pprovincias  implements java.io.Serializable {


     private BigDecimal idprovincia;
     private Pcomunidad pcomunidad;
     private String provincia;
     private Set pcodPobls = new HashSet(0);

    public Pprovincias() {
    }

	
    public Pprovincias(BigDecimal idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Pprovincias(BigDecimal idprovincia, Pcomunidad pcomunidad, String provincia, Set pcodPobls) {
       this.idprovincia = idprovincia;
       this.pcomunidad = pcomunidad;
       this.provincia = provincia;
       this.pcodPobls = pcodPobls;
    }
   
    public BigDecimal getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(BigDecimal idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Pcomunidad getPcomunidad() {
        return this.pcomunidad;
    }
    
    public void setPcomunidad(Pcomunidad pcomunidad) {
        this.pcomunidad = pcomunidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getPcodPobls() {
        return this.pcodPobls;
    }
    
    public void setPcodPobls(Set pcodPobls) {
        this.pcodPobls = pcodPobls;
    }




}


