/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.ResultSet;
import conexionunica.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Isabel
 */
public class JFDepartamentos extends javax.swing.JFrame {

    /**
     * Creates new form JFDepartamentos
     */
    private Conexion bd = Conexion.getInstance("oracle", "miravelesi", "bdisabel", "isabel", "isabel");
    private String idDepartamento;
    private boolean esNuevo = false;

    public JFDepartamentos(String idDepar) {
        idDepartamento = idDepar;
        if (idDepartamento.equals("0")) {
            esNuevo = true;
        }
        initComponents();
        rellenarCampos();
    }

    private void rellenarCampos() {
        try {
            if (!esNuevo) {
                String sql = "SELECT dept_no,dnombre,loc "
                        + "FROM DEPARTAMENTOS "
                        + "WHERE iddepartamento=" + idDepartamento;
                ResultSet resultado;
                try (Statement consulta = Conexion.conexion.createStatement()) {
                    resultado = consulta.executeQuery(sql);
                    resultado.next();
                    txtDeptNo.setText(resultado.getString("dept_no"));
                    txtDNombre.setText(resultado.getString("dnombre"));
                    txtLoc.setText(resultado.getString("loc"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFDepartamentos.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDeptNo = new javax.swing.JTextField();
        txtDNombre = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código Departamento");

        jLabel2.setText("Nombre Departamento");

        jLabel3.setText("Localidad");

        txtDeptNo.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        txtDeptNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptNoActionPerformed(evt);
            }
        });
        txtDeptNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeptNoFocusLost(evt);
            }
        });
        txtDeptNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeptNoKeyTyped(evt);
            }
        });

        txtDNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNombreFocusLost(evt);
            }
        });
        txtDNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNombreKeyTyped(evt);
            }
        });

        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });
        txtLoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLocFocusLost(evt);
            }
        });
        txtLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLocKeyTyped(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EXIT3.gif"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel4.setText("MENSAJE");

        txtMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(255, 0, 0));
        txtMensaje.setCaretColor(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGrabar)
                            .addGap(27, 27, 27)
                            .addComponent(btnSalir))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(txtLoc)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMensaje))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDeptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try {
            String sql;
            Statement consulta = bd.conexion.createStatement();
            if (!esNuevo) {
                sql = "UPDATE DEPARTAMENTOS  SET  dept_no=" + txtDeptNo.getText()
                        + ", dnombre='" + txtDNombre.getText()
                        + "', loc='" + txtLoc.getText()
                        + "'  WHERE iddepartamento=" + idDepartamento;
                int filas = consulta.executeUpdate(sql);
                consulta.close();
                salir();
            } else {
                Integer idDep = maximo("DEPARTAMENTOS", "IDDEPARTAMENTO") + 1;
                sql = "INSERT INTO DEPARTAMENTOS VALUES (" + idDep + "," + txtDeptNo.getText()
                        + ",'" + txtDNombre.getText() + "','" + txtLoc.getText() + "',0)";

                int filas = consulta.executeUpdate(sql);
                consulta.close();
                salir();
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFDepartamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        MantenimientoDepartamentos ventanaPrincipal;
        try {
            ventanaPrincipal = new MantenimientoDepartamentos();
            this.dispose();
            ventanaPrincipal.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JFDepartamentos.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtDeptNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeptNoKeyTyped
        if (txtDeptNo.getText().length() == 5) {
            evt.consume();
            txtMensaje.setText("Longitud Máxima: 5 caracteres");
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            txtMensaje.setText("COD. DEPART: Sólo números");
        }
        if (evt.getKeyChar() == '\b') {
            txtMensaje.setText("");
        }
    }//GEN-LAST:event_txtDeptNoKeyTyped

    private void txtDNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNombreKeyTyped

        if (txtDNombre.getText().length() == 50) {
            evt.consume();
            txtMensaje.setText("Longitud Máxima: 50 caracteres");
        }
        if (!Character.isSpaceChar(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            txtMensaje.setText("NOMBRE: Sólo caracteres alfabéticos");
        }
        if (evt.getKeyChar() == '\b') {
            txtMensaje.setText("");
        }

    }//GEN-LAST:event_txtDNombreKeyTyped

    private void txtLocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocKeyTyped
        if (txtLoc.getText().length() == 40) {
            evt.consume();
            txtMensaje.setText("Longitud Máxima: 40 caracteres");
        }
        if (!Character.isSpaceChar(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
            txtMensaje.setText("LOCALIDAD: Sólo caracteres alfabéticos");
        }
        if (evt.getKeyChar() == '\b') {
            txtMensaje.setText("");
        }
    }//GEN-LAST:event_txtLocKeyTyped

    private void txtDeptNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeptNoFocusLost
        txtMensaje.setText("");
    }//GEN-LAST:event_txtDeptNoFocusLost

    private void txtDNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNombreFocusLost
        txtMensaje.setText("");
    }//GEN-LAST:event_txtDNombreFocusLost

    private void txtLocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocFocusLost
        txtMensaje.setText("");
    }//GEN-LAST:event_txtLocFocusLost

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        btnGrabar.requestFocus();
    }//GEN-LAST:event_txtLocActionPerformed

    private void txtDeptNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptNoActionPerformed
        txtDNombre.requestFocus();
    }//GEN-LAST:event_txtDeptNoActionPerformed

    private void salir() {
        try {
            MantenimientoDepartamentos ventanaPrincipal = new MantenimientoDepartamentos();
            this.dispose();
            ventanaPrincipal.setVisible(true);


        } catch (SQLException ex) {
            Logger.getLogger(JFDepartamentos.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Integer maximo(String tabla, String id) throws SQLException {
        String sql = "SELECT MAX(" + id + ") maximo FROM " + tabla;
        ResultSet resultado;
        try (Statement consulta = Conexion.conexion.createStatement()) {
            resultado = consulta.executeQuery(sql);
            resultado.next();
            return resultado.getInt("maximo");
        }

    }

    private void limpiarDatos() {
        txtDeptNo.setText("");
        txtDNombre.setText("");
        txtLoc.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDNombre;
    private javax.swing.JTextField txtDeptNo;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
