/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_t2_act1_vis_empleados.y.max_salario;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import milibreria.swing.LAF;
import milibreria.swing.Limpiar;
import milibreria.swing.MiSwing;
import milibreria.swing.ValidacionesFormularios;

/**
 *
 * @author Alumno
 */
public class EmpleadosApp extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadosApp
     */
    public EmpleadosApp() {
        
        LAF.disenoGUI();
        
        modelo=new DefaultTableModel();
        
        initComponents();
        
        //conexion=new ConexionDB("OBDC", "", "", "", ""); //JDBC-MYSQL
        
        conexion=new ConexionDB("Oracle", "localhost", "C##AD", "A1234b", "orcl");
        //conexion=new ConexionDB("SQLite", "", "", "", "F:\\acceso de datos\\base de datos\\Ud2_TABLAS_EMPLE_DEPT_SQLITE.sql");
        //conexion=ConexionBDSingleton.getInstance("Oracle", "LOCALHOST", "ORADAM2", "alumno", "alumno");
        
        btnVisualizarEmpleados.setEnabled(false);
        
        btnLimpiar.setEnabled(false);
        
        btnSalario.setEnabled(false);
        
        txtNombreEmpleado.setEnabled(false);
        
        txtSalarioEmpleado.setEnabled(false);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoDep = new javax.swing.JTextField();
        btnVisualizarEmpleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtSalarioEmpleado = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        lblControl = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo Departamento: ");

        txtCodigoDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoDepKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoDepKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoDepKeyTyped(evt);
            }
        });

        btnVisualizarEmpleados.setText("Visualizar empleados");
        btnVisualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarEmpleadosActionPerformed(evt);
            }
        });

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        btnSalario.setText("Visualizar Empleado de mayor salario");
        btnSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Salario:");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblControl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoDep, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnVisualizarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarEmpleados)
                    .addComponent(btnLimpiar))
                .addGap(7, 7, 7)
                .addComponent(lblControl)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalario)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnVisualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarEmpleadosActionPerformed
        
        if (!conexion.existeValor(Integer.parseInt(txtCodigoDep.getText()), "DEPARTAMENTOS", "IDDEPARTAMENTO") ){
            JOptionPane.showMessageDialog(this, "Error, el departamento no existe");
        }else{
            
            //si la consulta obtiene 0 resultados nos lo indica
            if(conexion.consultaVaciaV2("select count(*) from Empleados e, departamentos d where e.IDDEPARTAMENTO=d.IDDEPARTAMENTO and IDDEPARTAMENTO="+txtCodigoDep.getText()+"")){
                 JOptionPane.showMessageDialog(this, "No hay resultados, prueba con otro valor");
            }else{
                
                //limpiamos la tabla para que no se acumulen los registros
                Limpiar.limpiarTabla(modelo);

                //ejecutamos la consulta y rellenamos la tabla
                conexion.ejecutarConsulta("select apellido,oficio,fecha_alt,salario  from Empleados e, departamentos d where e.IDDEPARTAMENTO=d.IDDEPARTAMENTO and IDDEPARTAMENTO="+txtCodigoDep.getText()+"");

                conexion.rellenaJTableBD(modelo);

                //Habilitamos y dehabilitamos controles
                txtCodigoDep.setEnabled(false);

                btnLimpiar.setEnabled(true);

                btnSalario.setEnabled(true);

                txtNombreEmpleado.setEnabled(true);

                txtSalarioEmpleado.setEnabled(true);
            }
            
            
            
        }
        
        
        
        
    }//GEN-LAST:event_btnVisualizarEmpleadosActionPerformed

    private void txtCodigoDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoDepKeyTyped
        
        ValidacionesFormularios.escribirSoloNumeros(evt, lblControl);
        
    }//GEN-LAST:event_txtCodigoDepKeyTyped

    private void btnSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalarioActionPerformed
        
        
        if (conexion.consultaVacia(modelo)){
                JOptionPane.showMessageDialog(this, "No hay reultados, prueba con otro valor");
        }else{
            conexion.ejecutarConsulta("select apellido, salario from Empleados where salario=(select max(salario) from empleados where IDDEPARTAMENTO=(select IDDEPARTAMENTO from departamentos where DEPT_NO="+txtCodigoDep.getText()+"))");

            try {
                //Escribimos el nombre y apellido del empleado con mas salario
                conexion.getResultSet().next();
                txtNombreEmpleado.setText(conexion.getResultSet().getString("apellido"));

                txtSalarioEmpleado.setText(String.valueOf(conexion.getResultSet().getInt("salario")));

            } catch (SQLException ex) {
                Logger.getLogger(EmpleadosApp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
       
    }//GEN-LAST:event_btnSalarioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar.limpiarTabla(modelo);

        //Habilitamos y deshabilitamos todos los botones necesarios
        txtCodigoDep.setEnabled(true);
        
         btnSalario.setEnabled(false);
        
        txtNombreEmpleado.setEnabled(false);
        
        btnLimpiar.setEnabled(false);
        
        txtSalarioEmpleado.setEnabled(false);
        
        txtNombreEmpleado.setText("");
        
        txtSalarioEmpleado.setText("");
    
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoDepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoDepKeyPressed
        
    }//GEN-LAST:event_txtCodigoDepKeyPressed

    private void txtCodigoDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoDepKeyReleased
       if (txtCodigoDep.getText().isEmpty()){
           btnVisualizarEmpleados.setEnabled(false);
        }else{
           btnVisualizarEmpleados.setEnabled(true);
        }
    }//GEN-LAST:event_txtCodigoDepKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalario;
    private javax.swing.JButton btnVisualizarEmpleados;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblControl;
    private javax.swing.JTextField txtCodigoDep;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSalarioEmpleado;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;
    private ConexionDB conexion;
    //private ConexionBDSingleton conexion; //Cambiar para singleton
}
