/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Isabel
 */
public class PC02_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PC02_MenuPrincipal
     */
    public PC02_MenuPrincipal() {
        initComponents();
        
        conexion=MiHibernateSingleton.getInstance();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jDeskPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuPacientes = new javax.swing.JMenuItem();
        MenuAnalisis = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuAnalRealiz = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examen 2ª Evaluación: Hibernate");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir22x22.png"))); // NOI18N

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/docs.gif"))); // NOI18N
        jMenu2.setText("Gestión");
        jMenu2.setBorderPainted(true);

        MenuPacientes.setText("Pacientes");
        MenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPacientesActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPacientes);

        MenuAnalisis.setText("Análisis");
        MenuAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAnalisisActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAnalisis);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sets.gif"))); // NOI18N
        jMenu3.setText("Análisis Realizados");
        jMenu3.setBorderPainted(true);

        MenuAnalRealiz.setText("Introducir Análisis");
        MenuAnalRealiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAnalRealizActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAnalRealiz);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAnalisisActionPerformed
      
        PC02_JD_IntroducirAnalisis ventana= new PC02_JD_IntroducirAnalisis();
       
        ventana.setVisible(true);
        
    }//GEN-LAST:event_MenuAnalisisActionPerformed

    private void MenuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPacientesActionPerformed
       
        jDeskPrincipal.removeAll();
        
        PC02_JI_GestionPacientes ventana=PC02_JI_GestionPacientes.getInstancia();
        
        jDeskPrincipal.add(ventana);
        
        ventana.show();
        
    }//GEN-LAST:event_MenuPacientesActionPerformed

    private void MenuAnalRealizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAnalRealizActionPerformed

       PC02_JD_AnalisisRealizados ventana=new PC02_JD_AnalisisRealizados(this, true);
       
       ventana.setVisible(true);
        
    }//GEN-LAST:event_MenuAnalRealizActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        conexion.getInstancia().close();
        System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PC02_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PC02_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PC02_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PC02_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PC02_MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAnalRealiz;
    private javax.swing.JMenuItem MenuAnalisis;
    private javax.swing.JMenuItem MenuPacientes;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JDesktopPane jDeskPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
    private static MiHibernateSingleton conexion;
}
