/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Modelos.Departamentos;
import Modelos.Empleados;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.neodatis.odb.ODB;
import org.neodatis.odb.ODBFactory;
import org.neodatis.odb.ObjectValues;
import org.neodatis.odb.Values;
import org.neodatis.odb.core.query.criteria.And;
import org.neodatis.odb.core.query.criteria.Where;
import org.neodatis.odb.impl.core.query.values.ValuesCriteriaQuery;

/**
 *
 * @author Isabel
 */
public class VisualizarEmpleados extends javax.swing.JFrame {

    public ODB odb = ODBFactory.open("EMPLEADOS.DB");// Abrir BD
    boolean inicio=true;
    /**
     * Creates new form VisualizarEmpleados
     */
    public VisualizarEmpleados() {
        initComponents();
        llenarDepartamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboDep = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jBtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Departamento");

        jCboDep.setToolTipText("");
        jCboDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboDepActionPerformed(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp_No", "Apellido", "Salario"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jBtonSalir.setText("Salir");
        jBtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(jCboDep, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtonSalir)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jBtonSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboDepActionPerformed

        borrartabla();
        String[] Seleccion = (String[]) jCboDep.getSelectedItem(); // Recoge lo seleccionado
        if ("-1".equals(Seleccion[0]) && !inicio) {
            JOptionPane.showMessageDialog(null, "Debe seleccioar un departamento");
        } else {
            if (!inicio) {
                Integer Dept_no = Integer.parseInt(Seleccion[0]);
                Values valores = odb.getValues(new ValuesCriteriaQuery(Empleados.class,
                        new And().add(Where.equal("dept.deptNo", Dept_no)))
                        .field("empNo")
                        .field("apellido")
                        .field("salario"));
                if (!valores.hasNext()) {
                    JOptionPane.showMessageDialog(null, "El departamento " + Seleccion[1] + "no tiene empleados");
                    jCboDep.requestFocus();
                    jCboDep.setSelectedIndex(0); // Coloca la selección al principio
                } else {
                    while (valores.hasNext()) {
                        ObjectValues objectValues = (ObjectValues) valores.next();
                        DefaultTableModel t = (DefaultTableModel) jTableEmpleados.getModel();
                        Object nuevo[] = {objectValues.getByAlias("empNo"), objectValues.getByAlias("apellido"), objectValues.getByAlias("salario")};
                        t.addRow(nuevo);
                    }
                }
            } else {
                inicio = false;
            }
        }
    }//GEN-LAST:event_jCboDepActionPerformed

    private void jBtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonSalirActionPerformed
        odb.close();
        System.exit(0);
    }//GEN-LAST:event_jBtonSalirActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    private void llenarDepartamentos() {
        String datos[] = new String[2];
        try {
            datos[0] = "-1";
            datos[1] = "Seleccionar";
            jCboDep.removeAllItems(); //Borra todos los Items
            jCboDep.addItem(new String[]{datos[0], datos[1],});
            Values valores = odb.getValues(new ValuesCriteriaQuery(Departamentos.class)
                    .field("deptNo")
                    .field("dnombre"));
            while (valores.hasNext()) {
                ObjectValues objectValues = (ObjectValues) valores.next();
                //Integer d= (Integer) objectValues.getByAlias("deptNo");;
                datos[0] = Integer.toString((Integer) objectValues.getByAlias("deptNo"));
                datos[1] = (String) objectValues.getByAlias("dnombre");
                jCboDep.addItem(new String[]{datos[0], datos[1],}); //Los aÃ±ade al Combo con dos columnas

            }

            jCboDep.setRenderer(new DefaultListCellRenderer() //Renderiza el Combo 
            {
                @Override
                public java.awt.Component getListCellRendererComponent(JList l, Object o, int i, boolean s, boolean f) {
                    return new JLabel(((String[]) o)[1]);  //Visualiza sÃ³lo la columna 1, que es el nombre
                }
            });


        } catch (Exception e) {
            System.out.println("error" + e);
        }


    }
     private void borrartabla(){
       int N=jTableEmpleados.getRowCount()-1;
       for (int i=N; i>=0;i--){
            DefaultTableModel temp = (DefaultTableModel) jTableEmpleados.getModel();
            temp.removeRow(i);
       }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* CreatVisualizarEmpleadosform */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarEmpleados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtonSalir;
    private javax.swing.JComboBox jCboDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
