package modelo;
// Generated 23-ene-2015 11:13:04 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Beditoriales generated by hbm2java
 */
public class Beditoriales  implements java.io.Serializable {


     private int ideditorial;
     private PcodPobl pcodPobl;
     private String nombre;
     private String direccion;
     private Integer telef1;
     private Integer telef2;
     private String email;
     private Boolean eliminado;
     private Set blibroses = new HashSet(0);

    public Beditoriales() {
    }

	
    public Beditoriales(int ideditorial, String nombre) {
        this.ideditorial = ideditorial;
        this.nombre = nombre;
    }
    public Beditoriales(int ideditorial, PcodPobl pcodPobl, String nombre, String direccion, Integer telef1, Integer telef2, String email, Boolean eliminado, Set blibroses) {
       this.ideditorial = ideditorial;
       this.pcodPobl = pcodPobl;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telef1 = telef1;
       this.telef2 = telef2;
       this.email = email;
       this.eliminado = eliminado;
       this.blibroses = blibroses;
    }
   
    public int getIdeditorial() {
        return this.ideditorial;
    }
    
    public void setIdeditorial(int ideditorial) {
        this.ideditorial = ideditorial;
    }
    public PcodPobl getPcodPobl() {
        return this.pcodPobl;
    }
    
    public void setPcodPobl(PcodPobl pcodPobl) {
        this.pcodPobl = pcodPobl;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelef1() {
        return this.telef1;
    }
    
    public void setTelef1(Integer telef1) {
        this.telef1 = telef1;
    }
    public Integer getTelef2() {
        return this.telef2;
    }
    
    public void setTelef2(Integer telef2) {
        this.telef2 = telef2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set getBlibroses() {
        return this.blibroses;
    }
    
    public void setBlibroses(Set blibroses) {
        this.blibroses = blibroses;
    }
    
     @Override
    public String toString(){
        return nombre;
    }




}


