package modelo;
// Generated 23-ene-2015 11:13:04 by Hibernate Tools 3.6.0



/**
 * Bmultasprestamos generated by hbm2java
 */
public class Bmultasprestamos  implements java.io.Serializable {


     private BmultasprestamosId id;
     private Bprestamos bprestamos;
     private Bmultas bmultas;
     private Character pagada;
     private Integer fechapago;
     private Integer eliminado;

    public Bmultasprestamos() {
    }

	
    public Bmultasprestamos(BmultasprestamosId id, Bprestamos bprestamos, Bmultas bmultas) {
        this.id = id;
        this.bprestamos = bprestamos;
        this.bmultas = bmultas;
    }
    public Bmultasprestamos(BmultasprestamosId id, Bprestamos bprestamos, Bmultas bmultas, Character pagada, Integer fechapago, Integer eliminado) {
       this.id = id;
       this.bprestamos = bprestamos;
       this.bmultas = bmultas;
       this.pagada = pagada;
       this.fechapago = fechapago;
       this.eliminado = eliminado;
    }
   
    public BmultasprestamosId getId() {
        return this.id;
    }
    
    public void setId(BmultasprestamosId id) {
        this.id = id;
    }
    public Bprestamos getBprestamos() {
        return this.bprestamos;
    }
    
    public void setBprestamos(Bprestamos bprestamos) {
        this.bprestamos = bprestamos;
    }
    public Bmultas getBmultas() {
        return this.bmultas;
    }
    
    public void setBmultas(Bmultas bmultas) {
        this.bmultas = bmultas;
    }
    public Character getPagada() {
        return this.pagada;
    }
    
    public void setPagada(Character pagada) {
        this.pagada = pagada;
    }
    public Integer getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Integer fechapago) {
        this.fechapago = fechapago;
    }
    public Integer getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Integer eliminado) {
        this.eliminado = eliminado;
    }




}


