package modelo;
// Generated 23-ene-2015 11:13:04 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pcodigopostales generated by hbm2java
 */
public class Pcodigopostales  implements java.io.Serializable {


     private int idcodPostal;
     private String codPostal;
     private Set pcodPobls = new HashSet(0);

    public Pcodigopostales() {
    }

	
    public Pcodigopostales(int idcodPostal, String codPostal) {
        this.idcodPostal = idcodPostal;
        this.codPostal = codPostal;
    }
    public Pcodigopostales(int idcodPostal, String codPostal, Set pcodPobls) {
       this.idcodPostal = idcodPostal;
       this.codPostal = codPostal;
       this.pcodPobls = pcodPobls;
    }
   
    public int getIdcodPostal() {
        return this.idcodPostal;
    }
    
    public void setIdcodPostal(int idcodPostal) {
        this.idcodPostal = idcodPostal;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public Set getPcodPobls() {
        return this.pcodPobls;
    }
    
    public void setPcodPobls(Set pcodPobls) {
        this.pcodPobls = pcodPobls;
    }
    
     @Override
    public String toString(){
        return codPostal;
    }




}


