package modelo;
// Generated 23-ene-2015 11:13:04 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pcomunidad generated by hbm2java
 */
public class Pcomunidad  implements java.io.Serializable {


     private int idcomunidad;
     private String nombreCom;
     private Set pprovinciases = new HashSet(0);

    public Pcomunidad() {
    }

	
    public Pcomunidad(int idcomunidad) {
        this.idcomunidad = idcomunidad;
    }
    public Pcomunidad(int idcomunidad, String nombreCom, Set pprovinciases) {
       this.idcomunidad = idcomunidad;
       this.nombreCom = nombreCom;
       this.pprovinciases = pprovinciases;
    }
   
    public int getIdcomunidad() {
        return this.idcomunidad;
    }
    
    public void setIdcomunidad(int idcomunidad) {
        this.idcomunidad = idcomunidad;
    }
    public String getNombreCom() {
        return this.nombreCom;
    }
    
    public void setNombreCom(String nombreCom) {
        this.nombreCom = nombreCom;
    }
    public Set getPprovinciases() {
        return this.pprovinciases;
    }
    
    public void setPprovinciases(Set pprovinciases) {
        this.pprovinciases = pprovinciases;
    }
    
     @Override
    public String toString(){
        return nombreCom;
    }




}


