/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Frame;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import modelos.ExArticulos;

/**
 *
 * @author Isabel
 */
public class PC02_JD_Articulos extends javax.swing.JDialog {

    /**
     * Creates new form PCXX_JD_Articulos
     */
    
    public PC02_JD_Articulos() {
       
        this.setModal(true);
        
         initComponents();
        
         codigoOperacion=INSERTAR;
         
         conexion=PC02_MenuPrincipal.devolverConexion();
         descripcionIncial="";
         
         
    }
    
    
    public PC02_JD_Articulos(int id) {
    
        this.setModal(true);
        
        initComponents();

        idArticuloActual=id;
         
        codigoOperacion=MODIFICAR;

        conexion=PC02_MenuPrincipal.devolverConexion();

        rellenarDatos();
        
    }
    
    
    public void rellenarDatos(){
        
        conexion.abrirSesion();
        
        ExArticulos art = (ExArticulos)conexion.getSesion().load(ExArticulos.class, idArticuloActual);
        
        txtDescrArtic.setText(art.getDescrArtic());
        txtPrecioUnitario.setText(String.valueOf(art.getPrecioUnitario().doubleValue()));
        
        descripcionIncial=art.getDescrArtic();
        
        conexion.cerrarSesion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescrArtic = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblControlDescripcion = new javax.swing.JLabel();
        lblControlPrecio = new javax.swing.JLabel();
        lblControlLongitudDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Articulos");

        jLabel1.setText("Descripción");

        jLabel2.setText("Precio Unitario");

        txtDescrArtic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescrArticKeyTyped(evt);
            }
        });

        txtPrecioUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUnitarioActionPerformed(evt);
            }
        });
        txtPrecioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioUnitarioKeyTyped(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addition.gif"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir22x22.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGrabar)
                                .addGap(82, 82, 82)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescrArtic, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblControlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblControlLongitudDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblControlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDescrArtic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblControlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblControlLongitudDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblControlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioActionPerformed
       
       
    }//GEN-LAST:event_txtPrecioUnitarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       
        
        String error="";
        
        Object matriz[][]={ {txtDescrArtic, txtPrecioUnitario},
                            {"- Escribe una descripcion /n", "- Escribe un precio /n"}
        };
        
        error+=MetodosComunes.comprobarVacios(matriz);
        
        if(conexion.ExisteValor(txtDescrArtic.getText().toUpperCase(), "descrArtic", "ExArticulos") && !descripcionIncial.equals(txtDescrArtic.getText().toUpperCase())){
            error+="-El articulo ya existe";
        }
        
        if(error.equals("")){
            
            
            ExArticulos art;
            
            String descripcion=txtDescrArtic.getText().toUpperCase();
            BigDecimal precio=new BigDecimal(txtPrecioUnitario.getText());
            String mensaje;
            
            conexion.abrirSesionYTransaccion();
            
            if(codigoOperacion==INSERTAR){
                
                idArticuloActual=conexion.proximoIDDisponible("idarticulo", "ExArticulos");
                
                art=new ExArticulos();
                art.setIdarticulo(idArticuloActual);
                
                art.setDescrArtic(descripcion);
                art.setPrecioUnitario(precio);
                
                art.setEliminado(false);
                
                mensaje="Articulo añadido";
                
                conexion.insertar(art);
                
            }else{
                
                art = (ExArticulos)conexion.getSesion().load(ExArticulos.class, idArticuloActual);
                
                art.setDescrArtic(descripcion);
                art.setPrecioUnitario(precio);
                
                mensaje="Articulo modificado";
                
                conexion.update(art);
                
            }
            
            conexion.cerrarSesionYTransaccion();
            
            JOptionPane.showMessageDialog(this, mensaje);
            
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, error);
        }
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtDescrArticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescrArticKeyTyped

        MetodosComunes.noEscribirMasDe(txtDescrArtic, 50, evt, lblControlLongitudDescripcion);
        MetodosComunes.escribirAlfanumerico(evt, lblControlDescripcion);
        
    }//GEN-LAST:event_txtDescrArticKeyTyped

    private void txtPrecioUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioKeyTyped

        MetodosComunes.escribirSoloDoubles(txtPrecioUnitario, evt, lblControlPrecio, 6,2);
        
    }//GEN-LAST:event_txtPrecioUnitarioKeyTyped

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblControlDescripcion;
    private javax.swing.JLabel lblControlLongitudDescripcion;
    private javax.swing.JLabel lblControlPrecio;
    private javax.swing.JTextField txtDescrArtic;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
   private int idArticuloActual;
   private String descripcionIncial;
   private int codigoOperacion;
   private final int INSERTAR=0;
   private final int MODIFICAR=1;
   private MiHibernate conexion;
   
}
