/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import java.awt.Frame;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Blibros;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author ALUMNOM
 */
public class JI_Libros extends javax.swing.JInternalFrame {

    //public SessionFactory instanciaHibernate = HibernateUtil.getSessionFactory();
    private static JI_Libros instancia;
    public DefaultTableModel tablaLibros;
    public static JI_Libros getInstancia() {
        // Si la instancia no está creada o la ventana está cerrada se crea la instancia

        if (instancia == null) {
            instancia = new JI_Libros();
        }
        return instancia;
    }
    /**
     * Creates new form JI_Libros
     */
    private JI_Libros() {
        initComponents();
        tablaLibros = (DefaultTableModel) jTableLibros.getModel();
        llenarTablaLibrosInicioHibernate();
    }
    
     
     private void llenarTablaLibrosInicioHibernate(){
         String sql =  " FROM Blibros l WHERE l.eliminado=0 ORDER BY l.titulo";
         llenarTablaLibrosHibernate(sql);
     }
     private void filtrar(){
        
         String sql = " FROM Blibros l ";
         
         if (radioEliminados.isSelected()) {
            sql = sql + " WHERE l.eliminado =1";
        } else {
            sql = sql + " WHERE l.eliminado =0";
        }
         if(txtISBN.getText().length() > 0){
             sql = sql + " and upper(l.isbn) like '%" + txtISBN.getText().toUpperCase() + "%'";
         }
         if(txtTitulo.getText().length() > 0){
             sql = sql + " and upper(l.titulo) like '%" + txtTitulo.getText().toUpperCase() + "%'";
         }
         if(txtEditorial.getText().length() > 0){
             sql = sql + " and upper(l.beditoriales.nombre) like '%" + txtEditorial.getText().toUpperCase() + "%'";
         }
         if(txtAutores.getText().length() > 0){
             sql = sql + " and upper(l.autores) like '%" + txtAutores.getText().toUpperCase() + "%'";
         }
         if(txtMateria.getText().length() > 0){
             sql = sql + " and upper(l.bmaterias.descmateria) like '%" + txtMateria.getText().toUpperCase() + "%'";
         }
          sql = sql + " order by l.titulo";
        
            llenarTablaLibrosHibernate(sql);
        
          
     }
     
     
      
      private void llenarTablaLibrosHibernate(String sql){
          limpiarTabla(tablaLibros);
          Session sesion = JF_Menu.instanciaHibernate.openSession();
          Query consulta = sesion.createQuery(sql);
          Iterator iter = consulta.iterate();
          while(iter.hasNext()){
              Blibros lib = (Blibros)iter.next();
              
              Object nuevo[] = {Integer.toString(lib.getIdlibro()),Long.toString(lib.getIsbn())
                                ,lib.getTitulo(),lib.getIdioma(),lib.getNrocopiastot(),lib.getBeditoriales().getNombre()
                                ,lib.getAutores(),lib.getBmaterias().getDescmateria()};
              tablaLibros.addRow(nuevo);
          }
          sesion.close();
          setOcultarColumnasJTable(jTableLibros,new int[]{0});
      }
      
      
    public static void setOcultarColumnasJTable(JTable tbl, int columna[]) {
        for (int i = 0; i < columna.length; i++) {
            tbl.getColumnModel().getColumn(columna[i]).setMaxWidth(0);
            tbl.getColumnModel().getColumn(columna[i]).setMinWidth(0);
            tbl.getTableHeader().getColumnModel().getColumn(columna[i]).setMaxWidth(0);
            tbl.getTableHeader().getColumnModel().getColumn(columna[i]).setMinWidth(0);
        }
    }
      
      private void limpiarTabla(DefaultTableModel tabla) {
        int a = tabla.getRowCount() - 1;  //Índices van de 0 a n-1
        for (int i = a; i >= 0; i--) {
            tabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAutores = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();
        radioEliminados = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("LIBROS");

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdLibro", "ISBN", "Titulo", "Idioma", "Nº Copias", "Editorial", "Autores", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLibros);

        jLabel1.setText("ISBN:");

        txtISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtISBNFocusLost(evt);
            }
        });
        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtISBNKeyReleased(evt);
            }
        });

        jLabel2.setText("Título:");

        jLabel3.setText("FILTROS");

        txtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTituloFocusLost(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloKeyReleased(evt);
            }
        });

        jLabel4.setText("Editorial:");

        txtEditorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEditorialFocusLost(evt);
            }
        });
        txtEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditorialKeyReleased(evt);
            }
        });

        jLabel5.setText("Autores:");

        txtAutores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAutoresFocusLost(evt);
            }
        });
        txtAutores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAutoresKeyReleased(evt);
            }
        });

        jLabel6.setText("Materia:");

        txtMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMateriaFocusLost(evt);
            }
        });
        txtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMateriaKeyReleased(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EXIT_ (23).jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnLimpiarFiltros.setText("Limpiar Filtros");
        btnLimpiarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltrosActionPerformed(evt);
            }
        });

        radioEliminados.setText("Eliminados");
        radioEliminados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioEliminadosStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnLimpiarFiltros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(radioEliminados, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFiltros))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioEliminados)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtISBNKeyReleased

    private void txtISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtISBNFocusLost
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtISBNFocusLost

    private void txtTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloFocusLost
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtTituloFocusLost

    private void txtEditorialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditorialFocusLost
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtEditorialFocusLost

    private void txtAutoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutoresFocusLost
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtAutoresFocusLost

    private void txtMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMateriaFocusLost
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtMateriaFocusLost

    private void txtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtTituloKeyReleased

    private void txtEditorialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditorialKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtEditorialKeyReleased

    private void txtAutoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutoresKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtAutoresKeyReleased

    private void txtMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtMateriaKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        JD_LibroNuevo dialogLibroNuevo =  new JD_LibroNuevo(f,true,"0");
        dialogLibroNuevo.dispose();
        dialogLibroNuevo.setVisible(true);
        // Actualizamos el jTable
        llenarTablaLibrosInicioHibernate();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         if (jTableLibros.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay Libros");
        } else {
            if (jTableLibros.getSelectedRow() != -1) {
                //devuelve el valor de la fila selecciona y la columna que es código departamento
                String idLibro = String.valueOf(jTableLibros.getValueAt(jTableLibros.getSelectedRow(), 0));
                Frame f = JOptionPane.getFrameForComponent(this);
                JD_LibroNuevo libroNuevo = new JD_LibroNuevo(f,true,idLibro);
                libroNuevo.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguno");
            }
        }
         llenarTablaLibrosInicioHibernate();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
         if (radioEliminados.isSelected()) {
            eliminarHibernate(false, "restaurar");
        } else {
            eliminarHibernate(true, "eliminar");
        }
       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLimpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltrosActionPerformed
        limpiarFiltros();
        llenarTablaLibrosInicioHibernate();
    }//GEN-LAST:event_btnLimpiarFiltrosActionPerformed

    private void radioEliminadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioEliminadosStateChanged
        // TODO add your handling code here:
        if (radioEliminados.isSelected()) {
            btnEliminar.setText("Restaurar");
        } else {
            btnEliminar.setText("Eliminar");
        }
        filtrar();
    }//GEN-LAST:event_radioEliminadosStateChanged
    private void limpiarFiltros(){
        txtISBN.setText("");
        txtTitulo.setText("");
        txtEditorial.setText("");
        txtAutores.setText("");
        txtMateria.setText("");  
    }

    public void eliminarHibernate(boolean eliminado, String texto) {
        if (jTableLibros.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay libros");
        } else {

            if (jTableLibros.getSelectedRow() != -1) {
                
                //devuelve el valor de la fila selecciona y la columna 0
                int fila = jTableLibros.getSelectedRow();

               
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea "+texto+" el registro : " + jTableLibros.getValueAt(fila, 2) + "?");
                    Session sesion = JF_Menu.instanciaHibernate.openSession();
                    if (opcion == JOptionPane.YES_OPTION) {
                        Transaction tx = sesion.beginTransaction();
                        Blibros lib = new Blibros();
                        lib = (Blibros)sesion.get(Blibros.class,Integer.parseInt(jTableLibros.getValueAt(fila,0).toString()));
                        lib.setEliminado(eliminado);
                        tx.commit();
                        System.out.println("Libro "+jTableLibros.getValueAt(fila, 0)+" borrado");
                        tablaLibros.removeRow(fila);
                        String texto1 = "";
                        if(texto.equals("eliminar")){
                            texto1 = "eliminado";
                        }else{
                            texto1 = "restaurado";
                        }
                        JOptionPane.showMessageDialog(null, "Registro "+texto1);

                    }
                    sesion.close();
                    
            } else {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguno");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarFiltros;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibros;
    private javax.swing.JRadioButton radioEliminados;
    private javax.swing.JTextField txtAutores;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
