/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ud02_jtable_visualizaremple;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isabel
 */
public class VisualizarEmpleados extends javax.swing.JFrame {

    public ConexionBd bd = new ConexionBd();
    public Connection conexion = bd.conectar("oracle", "LOCALHOST", "ORADAM2", "alumno", "alumno");
    public DefaultTableModel t;

    /**
     * Creates new form TablaEmpleados
     */
    public VisualizarEmpleados() {

        initComponents();
        t = (DefaultTableModel) JTableEmpleados.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDept_no = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableEmpleados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        txtVisualizarEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo Departamento");

        txtDept_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDept_noActionPerformed(evt);
            }
        });
        txtDept_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDept_noFocusGained(evt);
            }
        });
        txtDept_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDept_noKeyTyped(evt);
            }
        });

        JTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo Empleado", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableEmpleados);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EXIT_ (23).gif"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtVisualizarEmpleados.setText("Visualizar");
        txtVisualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisualizarEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDept_no, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVisualizarEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDept_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVisualizarEmpleados))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDept_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDept_noActionPerformed
        visualizarEmpleados();
    }//GEN-LAST:event_txtDept_noActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        bd.cerrar();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtDept_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDept_noKeyTyped
        if (txtDept_no.getText().length() == 5) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_txtDept_noKeyTyped

    private void txtVisualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisualizarEmpleadosActionPerformed
        visualizarEmpleados();
    }//GEN-LAST:event_txtVisualizarEmpleadosActionPerformed

    private void txtDept_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDept_noFocusGained

        txtDept_no.setText("");
    }//GEN-LAST:event_txtDept_noFocusGained

    private void visualizarEmpleados() {
        try {
            limpiarTabla(t);
            Integer id = buscarIdDepartamento(txtDept_no.getText());
            if (id == 0) { //No existe el Departamento
                JOptionPane.showMessageDialog(null, "No existe este Departamentoo está vacío");
            } else {
                String sql = "select emp_no,apellido from empleados where iddepartamento=?";
                PreparedStatement sentencia = conexion.prepareStatement(sql);
                sentencia.setString(1, id.toString());
                ResultSet resultado = sentencia.executeQuery();
                while (resultado.next()) {
                    //String M[]={resultado.getString(1),resultado.getString(2)};
                    Object nuevo[] = {resultado.getInt(1), resultado.getString(2)};
                    t.addRow(nuevo);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(VisualizarEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarTabla(DefaultTableModel tabla) {
        //int N = jTableEmpleados.getRowCount() - 1;
        int N = tabla.getRowCount() - 1;
        for (int i = N; i >= 0; i--) {
            tabla.removeRow(i);
        }
    }

    private int buscarIdDepartamento(String dep) throws SQLException {
        if (!dep.isEmpty()) {
            String sql = "SELECT IDDEPARTAMENTO FROM DEPARTAMENTOS WHERE DEPT_NO=" + dep;
            Statement consulta = conexion.createStatement();
            ResultSet resultado = consulta.executeQuery(sql);
            Boolean encontrado = resultado.next();
            if (!encontrado) {
                return 0;
            } else {
                return resultado.getInt("iddepartamento");

            }
        } else {
            return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VisualizarEmpleados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableEmpleados;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDept_no;
    private javax.swing.JButton txtVisualizarEmpleados;
    // End of variables declaration//GEN-END:variables
}
