/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionbiblioteca;

/**
 *
 * @author Aitor
 */
public class JIeditoriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIeditoriales
     */
    public JIeditoriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTeditoriales = new javax.swing.JTable();
        jBcerrar = new javax.swing.JButton();
        jBteliminar = new javax.swing.JButton();
        jBtanadir = new javax.swing.JButton();
        jCHKmoseliminados = new javax.swing.JCheckBox();
        jBtmodificar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1300, 600));
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(1300, 600));

        jTeditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDEDITORIAL", "NOMBRE", "DIRECCIÓN", "CÓDIGO POSTAL", "TELÉFONO 1", "TELÉFONO 2", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTeditoriales.setColumnSelectionAllowed(true);
        jTeditoriales.setPreferredSize(new java.awt.Dimension(1300, 600));
        jScrollPane1.setViewportView(jTeditoriales);
        jTeditoriales.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jBcerrar.setText("Cerrar Ventana");

        jBteliminar.setText("Eliminar");

        jBtanadir.setText("Añadir");

        jCHKmoseliminados.setText("Mostrar eliminados");

        jBtmodificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtanadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBteliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCHKmoseliminados)
                    .addComponent(jBcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtanadir)
                        .addGap(33, 33, 33)
                        .addComponent(jBtmodificar)
                        .addGap(28, 28, 28)
                        .addComponent(jBteliminar)
                        .addGap(47, 47, 47)
                        .addComponent(jCHKmoseliminados)
                        .addGap(249, 249, 249)
                        .addComponent(jBcerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcerrar;
    private javax.swing.JButton jBtanadir;
    private javax.swing.JButton jBteliminar;
    private javax.swing.JButton jBtmodificar;
    private javax.swing.JCheckBox jCHKmoseliminados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTeditoriales;
    // End of variables declaration//GEN-END:variables
}
