/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionbiblioteca;

import gestionbiblioteca.bbdd.ConexionBDSingleton;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import gestionbiblioteca.auxiliar.Auxiliar;


/**
 *
 * @author Aitor
 */
public class JImaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form JImaterias
     */
    
    DefaultTableModel dft;
    
    public JImaterias() {
        initComponents();
        dft=(DefaultTableModel) jTmaterias.getModel();
        jTmaterias.setModel(dft);
        cargarTabla();
    }
    
    
    private void cargarTabla(){
        String sql = "SELECT IDMATERIA,DESCMATERIA FROM BMATERIAS WHERE"+
                " ELIMINADO=0 ORDER BY DESCMATERIA";
        recargarTabla(sql);
    }
    
    private void recargarTabla(String sql) {
        Auxiliar.limpiarTabla(dft);
        ResultSet rs;
        try (Statement consulta = ConexionBDSingleton.conexion.createStatement()) {
            rs = consulta.executeQuery(sql);
            while (rs.next()) {
                dft.addRow(new Object[]{rs.getInt("IDMATERIA"), rs.getString("DESCMATERIA")});
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(JImaterias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
   
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTmaterias = new javax.swing.JTable();
        jBtanadir = new javax.swing.JButton();
        jBteliminar = new javax.swing.JButton();
        jBtmodificar = new javax.swing.JButton();
        jCHKmoseliminados = new javax.swing.JCheckBox();
        jBcerrar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1300, 600));
        setPreferredSize(new java.awt.Dimension(1300, 600));

        jTmaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IDMATERIA", "DESCRIPCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTmaterias.setPreferredSize(new java.awt.Dimension(1300, 588));
        jScrollPane1.setViewportView(jTmaterias);

        jBtanadir.setText("Añadir");

        jBteliminar.setText("Eliminar");

        jBtmodificar.setText("Modificar");

        jCHKmoseliminados.setText("Mostrar eliminados");

        jBcerrar.setText("Cerrar Ventana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtanadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBteliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jBtmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jCHKmoseliminados)
                    .addComponent(jBcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtanadir)
                        .addGap(33, 33, 33)
                        .addComponent(jBtmodificar)
                        .addGap(28, 28, 28)
                        .addComponent(jBteliminar)
                        .addGap(47, 47, 47)
                        .addComponent(jCHKmoseliminados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBcerrar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcerrar;
    private javax.swing.JButton jBtanadir;
    private javax.swing.JButton jBteliminar;
    private javax.swing.JButton jBtmodificar;
    private javax.swing.JCheckBox jCHKmoseliminados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTmaterias;
    // End of variables declaration//GEN-END:variables

    
}
