/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabel
 */
public class PC02_JD_GestionVendedores extends javax.swing.JDialog {

    /**
     * Creates new form PCXX_GestionVendedores
     */
    
    

    public PC02_JD_GestionVendedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        conexion=ConexionBDSingleton.getInstance("Oracle", "localhost", "oradam2", "ad", "ad");
        
        conexion.rellenaComboBox2Columnas(comboZonas, "select idzona, nombre_zona from ex_zonas", "--Elije una zona--", "idzona", "nombre_zona");
        
    }

    
    public void rellenar(String consulta){
        
          conexion.ejecutarConsulta(consulta);
                    
            ResultSet aux=conexion.getResultSet();
          try {
              
            aux.next();

            idVendedorActual=aux.getInt("idvendedor");

            //txtDNI.setText(aux.getString("DNI"));
            
            txtNombreVend.setText(aux.getString("Nombre_vend"));

            txtDireccion.setText(aux.getString("direccion"));

            txtTelefono.setText(String.valueOf(aux.getInt("telefono")));

            MetodosComunes.asignarItemCmb2Columnas(comboZonas, aux.getInt("idzona"));

        } catch (SQLException ex) {
            Logger.getLogger(PC02_JD_GestionVendedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnFinal = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtNombreVend = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboZonas = new javax.swing.JComboBox();
        lblControlDNI = new javax.swing.JLabel();
        lblControlLongitudTelefono = new javax.swing.JLabel();
        lblControlNombre = new javax.swing.JLabel();
        lblLongitudNombre = new javax.swing.JLabel();
        lblControlLongitudDireccion = new javax.swing.JLabel();
        lblControlTelefono = new javax.swing.JLabel();
        lblControlLongitudDNI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Vendedores");

        jLabel1.setText("DNI");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("DIRECCIÓN");

        jLabel4.setText("TELÉFONO");

        btnInicio.setText("<<");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.setEnabled(false);

        btnSiguiente.setText(">");
        btnSiguiente.setEnabled(false);

        btnFinal.setText(">>");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir22x22.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deletion.gif"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNIFocusLost(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        txtNombreVend.setEnabled(false);
        txtNombreVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVendActionPerformed(evt);
            }
        });
        txtNombreVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreVendKeyTyped(evt);
            }
        });

        txtDireccion.setEnabled(false);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtTelefono.setEnabled(false);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addition.gif"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setEnabled(false);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jLabel5.setText("ZONA");

        comboZonas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Zona" }));
        comboZonas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboZonas, 0, 405, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrabar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblControlDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblControlLongitudDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(txtNombreVend, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblControlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblControlLongitudDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLongitudNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSiguiente)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFinal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblControlTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lblControlLongitudTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblControlDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblControlLongitudDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblControlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblLongitudNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlLongitudDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblControlTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblControlLongitudTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnFinal)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar)
                    .addComponent(btnGrabar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        
        btnSiguiente.setEnabled(false);
        btnAnterior.setEnabled(true);
        
        rellenar("select * from (select * from ex_vendedores where dni<'"+txtDNI.getText().toUpperCase()+"') where rownum=1");
        
        
    }//GEN-LAST:event_btnFinalActionPerformed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        
        if(evt.getKeyCode()!=KeyEvent.VK_ENTER){
           MetodosComunes.escribirAlfanumerico(evt, lblControlDNI);
            MetodosComunes.noEscribirMasDe(txtDNI, 9, evt, lblControlLongitudDNI);
        }
        
        
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtNombreVendKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreVendKeyTyped
       
        MetodosComunes.escribirSoloLetrasYEspacios(evt, lblControlNombre);
        MetodosComunes.noEscribirMasDe(txtNombreVend, 80, evt, lblLongitudNombre);
        
    }//GEN-LAST:event_txtNombreVendKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        
        MetodosComunes.noEscribirMasDe(txtDireccion, 100, evt, lblControlLongitudDireccion);
        
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusLost
        
        
        
        
        
    }//GEN-LAST:event_txtDNIFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        txtDNI.setText("");
        txtDireccion.setText("");
        txtNombreVend.setText("");
        txtTelefono.setText("");
        comboZonas.setSelectedIndex(0);
        
        txtDNI.setEnabled(true);
        txtDireccion.setEnabled(false);
        txtNombreVend.setEnabled(false);
        txtTelefono.setEnabled(false);
        comboZonas.setEnabled(true);
        
        btnSiguiente.setEnabled(false);
        btnAnterior.setEnabled(false);
        
        
        btnFinal.setEnabled(true);
        btnInicio.setEnabled(true);
        
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGrabar.setEnabled(false);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       
        String error="";
        
        Object matriz[][]={ {txtDNI, txtNombreVend},
                            {"- DNI no debe estar vacio", "- Nombre no debe estar vacio"}
                          };
        error+=MetodosComunes.comprobarVacios(matriz);
        
        
        if(MetodosComunes.devolverCodigoComboBox(comboZonas)==-1){
            error="- La zona se debe seleccionar\n";
        }
        
        if(conexion.existeValor(txtDNI.getText().toUpperCase(), "EX_vendedores", "DNI") && codigoOperacion==UPDATE){
            error="- El DNI ya existe\n";
        }
        
        
        if(error.equals("")){
            
            int codigoZona=MetodosComunes.devolverCodigoComboBox(comboZonas);
            
            
            if(codigoOperacion==INSERT){
                
                int idDisponible=conexion.proximoIDDisponible("idvendedor", "ex_vendedores");
                
                
                
                conexion.ejecutarInstruccion("insert into ex_vendedores values("
                                                +idDisponible+", "
                                                + " '"+txtDNI.getText().toUpperCase()+"', "
                                                + " '"+txtNombreVend.getText()+"',"
                                                + " '"+txtDireccion.getText()+"', "
                                                + ""+txtTelefono.getText()+", "
                                                + ""+codigoZona+", "
                                                + "0)");
                
                conexion.commit();
                
                
            }else{
                
                
                
                conexion.ejecutarInstruccion("update ex_vendedores "
                                                +"set DNI='"+txtDNI.getText().toUpperCase()+"', "
                                                + ", nombre_vend='"+txtNombreVend.getText()+"', "
                                                + "direccion='"+txtDireccion.getText()+"' , "
                                                + "telefono="+txtTelefono.getText()+", "
                                                + "idzona="+codigoZona+""
                                                + " where idvendedor="+idVendedorActual+"");
                                                
                conexion.commit();
                
            }
            
            JOptionPane.showMessageDialog(this, "Vendedor Grabado");
            
            
        }else{
            JOptionPane.showMessageDialog(this, error);
        }
        
        
        
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        MetodosComunes.escribirSoloNumeros(evt, lblControlTelefono);
        MetodosComunes.noEscribirMasDe(txtTelefono, 9, evt, lblControlLongitudTelefono);
        
        
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
       
        if(MetodosComunes.comprobarDNI(txtDNI.getText().toUpperCase())){
            
            

            if(conexion.existeValor(txtDNI.getText().toUpperCase(), "EX_VENDEDORES", "DNI")){
                
                if(conexion.devolverValorInt("eliminado", "ex_vendedores", "  DNI='"+txtDNI.getText().toUpperCase()+"'")==1){
                    JOptionPane.showMessageDialog(this, "El Vendedor esta eliminado");
                     txtDNI.requestFocus();
                }else{
                    
                    txtDNI.setEnabled(false);
                
                    txtDireccion.setEnabled(true);
                    txtNombreVend.setEnabled(true);
                    txtTelefono.setEnabled(true);

                    comboZonas.setEnabled(true);

                    btnGrabar.setEnabled(true);

                    btnNuevo.setEnabled(true);
                    
                    
                    btnEliminar.setEnabled(true);
                
                  codigoOperacion=UPDATE;
                    
                  rellenar("select idvendedor,nombre_vend, direccion, telefono, idzona from ex_vendedores where DNI='"+txtDNI.getText().toUpperCase()+"'");
                
                    
                }
                
                
            }else{
                
                codigoOperacion=INSERT;
                
            }
                
            
        }else{
            JOptionPane.showMessageDialog(this, "Error, el dni es incorrecto");
            txtDNI.requestFocus();
        }
        
        
        
        
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtNombreVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVendActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        
        int seleccion=JOptionPane.showConfirmDialog(this, "¿Desea eliminar?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        
        if(seleccion==JOptionPane.YES_OPTION){
             conexion.ejecutarInstruccion("update ex_vendedores set eliminado=1 where idVendedor="+idVendedorActual+"");
             conexion.commit();
             JOptionPane.showMessageDialog(this, "Vendedor eliminado");
        }
        
        txtDNI.setText("");
        txtDireccion.setText("");
        txtNombreVend.setText("");
        txtTelefono.setText("");
        comboZonas.setSelectedIndex(0);
        
        txtDNI.setEnabled(true);
        txtDireccion.setEnabled(false);
        txtNombreVend.setEnabled(false);
        txtTelefono.setEnabled(false);
        comboZonas.setEnabled(true);
        
        btnSiguiente.setEnabled(false);
        btnAnterior.setEnabled(false);
        
        
        btnFinal.setEnabled(true);
        btnInicio.setEnabled(true);
        
        btnNuevo.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGrabar.setEnabled(false);
       
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        
        btnSiguiente.setEnabled(true);
        btnAnterior.setEnabled(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PC02_JD_GestionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PC02_JD_GestionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PC02_JD_GestionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PC02_JD_GestionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PC02_JD_GestionVendedores dialog = new PC02_JD_GestionVendedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox comboZonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblControlDNI;
    private javax.swing.JLabel lblControlLongitudDNI;
    private javax.swing.JLabel lblControlLongitudDireccion;
    private javax.swing.JLabel lblControlLongitudTelefono;
    private javax.swing.JLabel lblControlNombre;
    private javax.swing.JLabel lblControlTelefono;
    private javax.swing.JLabel lblLongitudNombre;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreVend;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    private ConexionBDSingleton conexion;
    private int codigoOperacion;
    private final int INSERT=0;
    private final int UPDATE=1;
    private int idVendedorActual;
}
