/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isabel
 */
public class PC02_JI_GestionArticulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form PCXX_JI_GestionArticulos
     */
     private PC02_JI_GestionArticulos() {
        
         modelo=new DefaultTableModel(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
         
         initComponents();
        
        conexion=ConexionBDSingleton.getInstance("Oracle", "localhost", "oradam2", "ad", "ad");
        
        
       ButtonGroup grupo=new ButtonGroup();
        
        grupo.add(radioEliminado);
        grupo.add(radioNoEliminado);
        
        
        radioNoEliminado.setSelected(true);
        
        rellenaTabla(CONSULTA_INICIAL);
        
    }
     
     public static PC02_JI_GestionArticulos getInstancia() {

        if (instancia == null || instancia.isClosed) {
            instancia = new PC02_JI_GestionArticulos();
        }
        return instancia;
    }
     
     public void rellenaTabla(String consulta){
         
         
         MetodosComunes.limpiarTabla(modelo);
           
         
         conexion.ejecutarConsulta(consulta);
         
         conexion.rellenaJTableBD(modelo);
         
         MetodosComunes.ocultarColumnaJTable(TablaArticulos, 0);
         
         
         
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnTodos = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        radioEliminado = new javax.swing.JRadioButton();
        radioNoEliminado = new javax.swing.JRadioButton();
        txtDescr_Artic = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblControlLongitud = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestión de Articulos");

        TablaArticulos.setModel(modelo);
        TablaArticulos.setName("Articulos"); // NOI18N
        jScrollPane1.setViewportView(TablaArticulos);

        jLabel4.setText("Descripción");

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        radioEliminado.setText("Eliminados");

        radioNoEliminado.setText("No Eliminados");

        txtDescr_Artic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescr_ArticKeyTyped(evt);
            }
        });

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addition.gif"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deletion.gif"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir22x22.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescr_Artic, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioEliminado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioNoEliminado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(btnAñadir)
                            .addComponent(btnSalir))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblControlLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAñadir, btnEliminar, btnModificar, btnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescr_Artic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnFiltrar)
                    .addComponent(radioEliminado)
                    .addComponent(radioNoEliminado))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAñadir, btnEliminar, btnModificar, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        rellenaTabla(CONSULTA_INICIAL);
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
       
        
        String condicion="";
        
        
        if(radioEliminado.isSelected()){
            condicion="eliminado=1";
        }else{
            condicion="eliminado=0";
        }
        
        
        String consulta="";
        
        if(txtDescr_Artic.getText().equals("")){
            consulta="select idarticulo, descr_artic, precio_unitario from ex_articulos where "+condicion+" order by descr_artic";
       
        }else{
            consulta="select idarticulo, descr_artic, precio_unitario from ex_articulos where "+condicion+" and upper(descr_artic) like '%"+txtDescr_Artic.getText().toUpperCase()+"%' order by descr_artic";
       
        }
        
        rellenaTabla(consulta);
        
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtDescr_ArticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescr_ArticKeyTyped
        
        MetodosComunes.noEscribirMasDe(txtDescr_Artic, 50, evt, lblControlLongitud);
        
        
    }//GEN-LAST:event_txtDescr_ArticKeyTyped

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        
        PC02_JD_Articulos articulos=new PC02_JD_Articulos(-1);
        articulos.setVisible(true);
        
        rellenaTabla(CONSULTA_INICIAL);
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
       int fila=TablaArticulos.getSelectedRow();

            if(fila!=-1){

                BigDecimal idArticulo=(BigDecimal)TablaArticulos.getValueAt(fila, 0);

                PC02_JD_Articulos articulos=new PC02_JD_Articulos(idArticulo.intValue());
                articulos.setVisible(true);
                
                rellenaTabla(CONSULTA_INICIAL);
                
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int fila=TablaArticulos.getSelectedRow();

            if(fila!=-1){

                BigDecimal idArticulo=(BigDecimal)TablaArticulos.getValueAt(fila, 0);

                int seleccion=JOptionPane.showConfirmDialog(this, "¿Estas seguro de que quieres eliminar el articulo?");
                
                if(seleccion==JOptionPane.YES_OPTION){
                    
                    conexion.ejecutarInstruccion("update ex_articulos set eliminado=1 where idarticulo="+idArticulo.intValue()+"");
                    
                    conexion.commit();
                    
                    JOptionPane.showMessageDialog(this, "Articulo borrado");
                    
                    rellenaTabla(CONSULTA_INICIAL);
                    
                }
                
                
                
            }else{
                JOptionPane.showMessageDialog(this, "No has selecccionado ninguna fila");
            }
        
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblControlLongitud;
    private javax.swing.JRadioButton radioEliminado;
    private javax.swing.JRadioButton radioNoEliminado;
    private javax.swing.JTextField txtDescr_Artic;
    // End of variables declaration//GEN-END:variables
    private static PC02_JI_GestionArticulos instancia;
    private DefaultTableModel modelo;
    private ConexionBDSingleton conexion;
    public final String CONSULTA_INICIAL="select idarticulo, descr_artic, precio_unitario from ex_articulos where eliminado=0 order by descr_artic";
}
