/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import clases.MiHibernateSingleton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class frmClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    private frmClientes() {
        
        String columnas[]={"codigocliente", "nombre cliente", "telefono", "linea direccion 1", "ciudad", "nombre empleado"};
        
        modelo=new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        initComponents();
        
        conexion=MiHibernateSingleton.getInstance();
        
        conexion.rellenarTablaObject(CONSULTA_CLIENTES, 6 , modelo);
        
    }
    
    public static frmClientes getInstancia() {

            if (instancia == null || instancia.isClosed) {
                instancia = new frmClientes();
            }
            return instancia;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;
    private static frmClientes instancia;
    private MiHibernateSingleton conexion;
    
    private String CONSULTA_CLIENTES="select c.codigocliente, c.nombrecliente, c.telefono, c.lineadireccion1, c.ciudad, em.nombre || ' ' || em.apellido1 || ' ' || em.apellido2 from Clientes c, Empleados em where c.empleados.codigoempleado=em.codigoempleado";
}