/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import clases.MiHibernateSingleton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class Pedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pedidos
     */
    private Pedidos() {
       
        String columnas[]={"codigo pedido", "fecha pedido", "fecha esperada", "fecha entrega", "estado", "cliente"};
        
        modelo=new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        initComponents();
        
        
        
        conexion=MiHibernateSingleton.getInstance();
        
        conexion.rellenarTablaObject(CONSULTA_PEDIDOS, 6, modelo);
        
    }
    
    public static Pedidos getInstancia() {

        if (instancia == null || instancia.isClosed) {
            instancia = new Pedidos();
        }
        return instancia;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();

        tablaPedidos.setModel(modelo);
        jScrollPane1.setViewportView(tablaPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
    private static Pedidos instancia;
    private DefaultTableModel modelo;
    private MiHibernateSingleton conexion;
    
    
    private final String CONSULTA_PEDIDOS="select p.codigopedido, p.fechapedido, p.fechaesperada, p.fechaentrega, p.estado, c.nombrecliente from Pedidos p, Clientes c where p.clientes.codigocliente=c.codigocliente";

}
