package modelos;
// Generated 24-feb-2014 18:09:26 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private PagosId id;
     private Clientes clientes;
     private String formapago;
     private Date fechapago;
     private BigDecimal cantidad;

    public Pagos() {
    }

    public Pagos(PagosId id, Clientes clientes, String formapago, Date fechapago, BigDecimal cantidad) {
       this.id = id;
       this.clientes = clientes;
       this.formapago = formapago;
       this.fechapago = fechapago;
       this.cantidad = cantidad;
    }
   
    public PagosId getId() {
        return this.id;
    }
    
    public void setId(PagosId id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(String formapago) {
        this.formapago = formapago;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


