package modelos;
// Generated 25-feb-2014 9:08:21 by Hibernate Tools 3.2.1.GA



/**
 * Hpaciente generated by hbm2java
 */
public class Hpaciente  implements java.io.Serializable {


     private int idpaciente;
     private String dni;
     private String nombrep;
     private String nrosegsoc;
     private String direccion;
     private String poblacion;
     private String provincia;
     private Integer fechanac;
     private char sexo;
     private boolean eliminado;

    public Hpaciente() {
    }

	
    public Hpaciente(int idpaciente, String dni, String nombrep, String nrosegsoc, char sexo, boolean eliminado) {
        this.idpaciente = idpaciente;
        this.dni = dni;
        this.nombrep = nombrep;
        this.nrosegsoc = nrosegsoc;
        this.sexo = sexo;
        this.eliminado = eliminado;
    }
    public Hpaciente(int idpaciente, String dni, String nombrep, String nrosegsoc, String direccion, String poblacion, String provincia, Integer fechanac, char sexo, boolean eliminado) {
       this.idpaciente = idpaciente;
       this.dni = dni;
       this.nombrep = nombrep;
       this.nrosegsoc = nrosegsoc;
       this.direccion = direccion;
       this.poblacion = poblacion;
       this.provincia = provincia;
       this.fechanac = fechanac;
       this.sexo = sexo;
       this.eliminado = eliminado;
    }
   
    public int getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombrep() {
        return this.nombrep;
    }
    
    public void setNombrep(String nombrep) {
        this.nombrep = nombrep;
    }
    public String getNrosegsoc() {
        return this.nrosegsoc;
    }
    
    public void setNrosegsoc(String nrosegsoc) {
        this.nrosegsoc = nrosegsoc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Integer getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Integer fechanac) {
        this.fechanac = fechanac;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public boolean isEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }




}


