
package formularios;


import clases.Idioma;
import clases.MiNeodatisSingleton;
import clases_bd.Categoria;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fernando
 */
public class AnadirCategoria extends javax.swing.JDialog {

    /**
     * Creates new form AnadirCategoria
     * @param frame
     * @param idioma
     */
    public AnadirCategoria(JFrame frame, Idioma idioma) {
        super(frame, true);
        
        initComponents();
        
        int x = (frame.getWidth() - this.getWidth()) / 2;
        int y = (frame.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
        
        this.idioma=idioma;
        //this.diccionario=diccionario;
        
        conexion=MiNeodatisSingleton.getInstance("Diccionario.db", "USR_DICCIONARIO", "123456");
        
        idioma(idioma);
    }
    
    private void idioma(Idioma idioma){
		
        this.setTitle(idioma.getProperty("anadirCategoria_titulo"));
        lblNombreDeLa.setText(idioma.getProperty("anadirCategoria_etiqueta"));
        anadir.setText(idioma.getProperty("anadirCategoria_botonOk"));
        anadirOtro.setText(idioma.getProperty("anadirCategoria_botonAnadirOtra"));
        cancelButton.setText(idioma.getProperty("anadirCategoria_botonCancel"));

    }
    
    public void anadir(){
        
         if(nombreCategoria.getText().equals("")){
            JOptionPane.showMessageDialog(this, idioma.getProperty("soporteTecnico_mensajeE1"),  idioma.getProperty("anadirTraduccion_tituloMensaje1"), JOptionPane.ERROR_MESSAGE);	
        }else{
            if(conexion.existeValorString(nombreCategoria.getText().toLowerCase(), "descripcion", "clases_bd.Categoria")){
                JOptionPane.showMessageDialog(this, idioma.getProperty("anadirCategoria_categoriaExistente"), idioma.getProperty("anadirTraduccion_tituloMensaje1"), JOptionPane.ERROR_MESSAGE);
            }else{
                
                int idCategoria=conexion.proximoId("idCategoria", "clases_bd.Categoria");
                
                Categoria categoria=new Categoria(idCategoria, getNombreCategoria().toLowerCase());
                conexion.guardarObjeto(categoria);
                conexion.commit();
                JOptionPane.showMessageDialog(this, idioma.getProperty("anadirCategoria_categoriaAnadida"), idioma.getProperty("tituloExitoPDF"), JOptionPane.INFORMATION_MESSAGE);
                
               
            }
        }
        
    }
    
    public void nuevo(){
        nombreCategoria.setText("");
        nombreCategoria.requestFocus();
    }
    
    public String getNombreCategoria() {
        return nombreCategoria.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        anadirOtro = new javax.swing.JButton();
        anadir = new javax.swing.JButton();
        nombreCategoria = new javax.swing.JTextField();
        lblNombreDeLa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        anadirOtro.setText("Añadir Otra");
        anadirOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirOtroActionPerformed(evt);
            }
        });

        anadir.setText("Añadir");
        anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirActionPerformed(evt);
            }
        });

        lblNombreDeLa.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNombreDeLa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anadirOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreDeLa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anadir)
                    .addComponent(anadirOtro)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        setVisible(false);

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void anadirOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirOtroActionPerformed
        anadir();
        nuevo();
    }//GEN-LAST:event_anadirOtroActionPerformed

    private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
       
        anadir();
        setVisible(false);
        
    }//GEN-LAST:event_anadirActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JButton anadirOtro;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel lblNombreDeLa;
    private javax.swing.JTextField nombreCategoria;
    // End of variables declaration//GEN-END:variables
    private MiNeodatisSingleton conexion;
    private Idioma idioma;
}
