package formularios;

import clases.Idioma;
import clases_bd.Traducciones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fernando
 */
public class BorrarTraduccion extends EditarYBorrarTraducciones {

    /**
     * Creates new form BorrarTraduccion
     * @param frame
     * @param idioma
     */
    public BorrarTraduccion(JFrame frame, Idioma idioma) {
        
        super(frame, idioma);
        this.setTitle(idioma.getProperty("borrarTraduccion_titulo"));
        initComponents();
        
        int x = (frame.getWidth() - this.getWidth()) / 2;
        int y = (frame.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
        
        buscaCoincidencias("");
        btnModEli.setText(idioma.getProperty("borrarTraduccion_borrar"));
        evento();
    }
    
    public void evento(){
        
        btnModEli.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent arg0) {
                
                if(listaCoincidencias.getSelectedValue()==null){
                   JOptionPane.showMessageDialog(frame, idioma.getProperty("borrarTraduccion_sinFilaSeleccionada"), idioma.getProperty("anadirTraduccion_tituloMensaje1"), JOptionPane.ERROR_MESSAGE); 
                }else{
                    
                    int eleccion=JOptionPane.showConfirmDialog(frame, idioma.getProperty("borrarTraduccion_mensajeConfirmar"), idioma.getProperty("borrarTraduccion_mensajeConfirmarTitulo"), JOptionPane.YES_NO_OPTION);
                    if(eleccion==JOptionPane.YES_OPTION){
                    
                        Traducciones traduActual=(Traducciones)listaCoincidencias.getSelectedValue();
                        
                        conexion.borrarObjeto(traduActual);
                        
                        conexion.commit();
                        
                        modelo.removeElement(traduActual);
                        JOptionPane.showMessageDialog(frame, idioma.getProperty("borrarTraduccion_borradoExito"), idioma.getProperty("borrarTraduccion_borradoExitoTitulo"), JOptionPane.INFORMATION_MESSAGE);
                        
                    }
                }
            }

        });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private JFrame frame;
}
