package formularios;


import clases.Idioma;
import clases_bd.Categoria;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fernando
 */
public class EditarCategoria extends EditarYBorrarCategorias {

    /**
     * Creates new form EditarCategoria
     * @param frame
     * @param idioma
     */
    public EditarCategoria(JFrame frame, Idioma idioma) {
        super(frame, idioma);
        initComponents();
        
        int x = (frame.getWidth() - this.getWidth()) / 2;
        int y = (frame.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
        
        this.frame=frame;
        buscaCoincidencias(busquedaPalabra.getText());
        idioma();
        eventosEspeciales();
        
        categoria.setText("");
        categoria.setEnabled(false);
    }

    
    
    private void eventosEspeciales(){
        
        btnModEli.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                if(listaCoincidencias.getSelectedValue()==null){
                   JOptionPane.showMessageDialog(frame, idioma.getProperty("borrarCategoria_sinFilaSeleccionada"), idioma.getProperty("anadirTraduccion_tituloMensaje1"), JOptionPane.ERROR_MESSAGE); 
                }else{
                    if(conexion.existeValorString(categoria.getText(), "descripcion", "clases_bd.Categoria")){
                        JOptionPane.showMessageDialog(frame, idioma.getProperty("anadirCategoria_categoriaExistente"), idioma.getProperty("editarCategoria_tituloExistente"), JOptionPane.ERROR_MESSAGE);
                    }else{
                        String antiguaCategoria=(String)listaCoincidencias.getSelectedValue();
                        
                        Categoria categoriaActual=(Categoria)conexion.devolverObjeto(antiguaCategoria, "descripcion", "clases_bd.Categoria");
                        categoriaActual.setDescripcion(categoria.getText());
                        
                        conexion.guardarObjeto(categoriaActual);
                        
                        conexion.commit();
                       
                        JOptionPane.showMessageDialog(frame, idioma.getProperty("editarCategoria_exito"), idioma.getProperty("editarCategoria_tituloExito"), JOptionPane.INFORMATION_MESSAGE);

                        buscaCoincidencias(busquedaPalabra.getText());
                    } 
                }
                

            }
			
        });
        
        
        listaCoincidencias.addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(listaCoincidencias.getSelectedValue()!=null){
                    String cadena=(String)listaCoincidencias.getSelectedValue();
                    categoria.setText(cadena);
                    categoria.setEnabled(true);
                }else{
                    categoria.setText("");
                    categoria.setEnabled(false);
                }
            }
            
        });
        
        
    }
    
    private void idioma(){
            
        panel.setBorder(BorderFactory.createTitledBorder(idioma.getProperty("editarTraduccion_tituloPanel")));
        this.setTitle(idioma.getProperty("editarCategoria_titulo"));
        lblNombreDeLa.setText(idioma.getProperty("anadirCategoria_etiqueta"));
        btnModEli.setText(idioma.getProperty("editarTraduccion_btnModificar"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        categoria = new javax.swing.JTextField();
        lblNombreDeLa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblNombreDeLa.setText("jLabel1");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNombreDeLa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreDeLa))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel lblNombreDeLa;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    private JFrame frame;
}
