/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_1º.ficheros_pc02_fernandureñagomez;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alumno
 */
public class Ejercicio2_Introducir_Peliculas_Serializ_PC02 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2_Introducir_Peliculas_Serializ_PC02
     */
    public Ejercicio2_Introducir_Peliculas_Serializ_PC02() {
        initComponents();
        
        String tipos[]={"Seleccione Tipo Pelicula", "Drama","Comedia", "Terror", "Accion", "Ficcion", "Melodrama", "Suspense"};
        
        MetodosComunes.rellenaComboBox(cmbTipoPelicula, tipos);
        
        campos=new JTextField[6];
        
        campos[0]=txtID;
        campos[1]=txtTitulo;
        campos[2]=txtAnio;
        campos[3]=txtDirector;
        campos[4]=txtNacionalidad;
        campos[5]=txtPresupuesto;
        
        
        
//        //le paso el numero total del registro, el fichero y el tipo de datos
//        claseFicheroAleatorio=new RAF(294, ficheroAleatorio, informacion);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtPresupuesto = new javax.swing.JTextField();
        cmbTipoPelicula = new javax.swing.JComboBox();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblControlID = new javax.swing.JLabel();
        lblControlTitulo = new javax.swing.JLabel();
        lblControlDirector = new javax.swing.JLabel();
        lblcontrolAnio = new javax.swing.JLabel();
        lblControlNacionalidad = new javax.swing.JLabel();
        lblControlPresupuesto = new javax.swing.JLabel();
        lblcontrolIDLongitud = new javax.swing.JLabel();
        lblControlTituloLongitud = new javax.swing.JLabel();
        lblcontrolAnioLongitud = new javax.swing.JLabel();
        lblControlDirectorLongitud = new javax.swing.JLabel();
        lblControlNacionalidadLongitud = new javax.swing.JLabel();
        lblControlPresupuestoLongitud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id pelicula");

        jLabel2.setText("Titulo");

        jLabel3.setText("año Produccion");

        jLabel4.setText("Director");

        jLabel5.setText("Nacionalidad");

        jLabel6.setText("Presupuesto");

        jLabel7.setText("Tipo pelicula");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        txtDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirectorKeyTyped(evt);
            }
        });

        txtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacionalidadKeyTyped(evt);
            }
        });

        txtPresupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPresupuestoKeyTyped(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblControlID))
                            .addComponent(txtTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcontrolAnio)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblControlNacionalidad)
                                    .addComponent(lblControlTitulo)
                                    .addComponent(lblControlTituloLongitud)
                                    .addComponent(lblControlNacionalidadLongitud)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblcontrolIDLongitud))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblControlDirectorLongitud)
                                    .addComponent(lblControlDirector)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(btnGrabar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(btnSalir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbTipoPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblControlPresupuesto)))
                                        .addGap(147, 147, 147)
                                        .addComponent(lblControlPresupuestoLongitud))))
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(lblcontrolAnioLongitud)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlID)
                    .addComponent(lblcontrolIDLongitud))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblControlTituloLongitud)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcontrolAnio)
                    .addComponent(lblcontrolAnioLongitud))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlDirector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblControlDirectorLongitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlNacionalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblControlNacionalidadLongitud)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControlPresupuesto)
                    .addComponent(lblControlPresupuestoLongitud))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbTipoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnSalir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
       
        if(evt.getKeyChar()==13){
        
        }else{
            MetodosComunes.escribirSoloNumeros(evt, lblControlID);
            MetodosComunes.noEscribirMasDe(txtID, 6, evt, lblcontrolIDLongitud);
        }
        
       
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        MetodosComunes.escribirSoloLetrasYEspacios(evt, lblControlTitulo);
        MetodosComunes.noEscribirMasDe(txtTitulo, 50, evt, lblControlTituloLongitud);
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        MetodosComunes.escribirSoloNumeros(evt, lblcontrolAnio);
        MetodosComunes.noEscribirMasDe(txtAnio, 4, evt, lblcontrolAnioLongitud);
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtDirectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirectorKeyTyped
        MetodosComunes.escribirSoloLetrasYEspacios(evt, lblControlDirector);
        MetodosComunes.noEscribirMasDe(txtDirector, 50, evt, lblControlDirectorLongitud);       
    }//GEN-LAST:event_txtDirectorKeyTyped

    private void txtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacionalidadKeyTyped
        MetodosComunes.escribirSoloLetrasYEspacios(evt, lblControlNacionalidad);
        MetodosComunes.noEscribirMasDe(txtNacionalidad, 40, evt, lblControlNacionalidadLongitud);  
    }//GEN-LAST:event_txtNacionalidadKeyTyped

    private void txtPresupuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresupuestoKeyTyped
        MetodosComunes.escribirSoloNumeros(evt, lblControlPresupuesto);
        MetodosComunes.noEscribirMasDe(txtPresupuesto, 6, evt, lblControlPresupuestoLongitud);
    }//GEN-LAST:event_txtPresupuestoKeyTyped

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        
        //Matriz con los campos y textos personalizados de error
        Object matriz[][]={
                                 {txtID, txtTitulo, txtDirector},
                                 {" El ID no puede estar vacio\n", 
                                    " El titulo no puede estar vacio\n",
                                        " El director no puede estar nulo\n"}
                                   
                                };
        
        
        String error=MetodosComunes.comprobarVacios(matriz);
        
        if(cmbTipoPelicula.getSelectedIndex()==0){
            error+=" Debes elegir un tipo de pelicula";
        }
        
        if(error.equals("")){
            
            char caracterPeli=cmbTipoPelicula.getSelectedItem().toString().charAt(0);
            
           
            int anio=0;
            int presupuesto=0;
            
            if(!txtAnio.getText().isEmpty()){
                anio=Integer.parseInt(txtAnio.getText());
            }
            
            if(!txtPresupuesto.getText().isEmpty()){
                presupuesto=Integer.parseInt(txtAnio.getText());
            }
            
            Peliculas peli=new Peliculas(Integer.parseInt(txtID.getText()),
                                            txtTitulo.getText(),
                                            anio,
                                            txtDirector.getText(),
                                            txtNacionalidad.getText(),
                                            presupuesto,
                                            caracterPeli);
            
            
            MetodosComunes.escribirFicheroSerializado(ficheroObjetos, peli);
            
            JOptionPane.showMessageDialog(this, "Registro Grabado");
            
            MetodosComunes.limpiaCampos(campos);
            
            cmbTipoPelicula.setSelectedIndex(0);
            
        }else{
            JOptionPane.showMessageDialog(this, error, "errores", JOptionPane.ERROR_MESSAGE);
        }
            
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
       
        
        
        
        
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        if(comprobarObjetoExistente(ficheroObjetos, Integer.parseInt(txtID.getText()))){
            JOptionPane.showMessageDialog(this, "La pelicula ya existe", "errores", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.setText("");
        }
        
        if(txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes escribir un id", "errores", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.setText("");
        }
        
    }//GEN-LAST:event_txtIDFocusLost


    
    public static boolean comprobarObjetoExistente(File fichero, int id){
        
        boolean existe=false;
        
        if(fichero.exists()){
            try(ObjectInputStream ois=new ObjectInputStream(new FileInputStream(fichero))){
               
            while(true){
                Peliculas peliActual=(Peliculas) ois.readObject();
                
                if(id==peliActual.getIdPelicula()){
                    existe=true;
                }
            }
           
            }catch(ClassNotFoundException e){
                System.out.println("Clase no encontrada");
            }catch(EOFException e){
                  
            }catch(IOException e){
                  System.out.println(e.getMessage());
            }
        }
        
        return existe;
        
    }
          
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_Introducir_Peliculas_Serializ_PC02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_Introducir_Peliculas_Serializ_PC02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_Introducir_Peliculas_Serializ_PC02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_Introducir_Peliculas_Serializ_PC02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2_Introducir_Peliculas_Serializ_PC02().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbTipoPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblControlDirector;
    private javax.swing.JLabel lblControlDirectorLongitud;
    private javax.swing.JLabel lblControlID;
    private javax.swing.JLabel lblControlNacionalidad;
    private javax.swing.JLabel lblControlNacionalidadLongitud;
    private javax.swing.JLabel lblControlPresupuesto;
    private javax.swing.JLabel lblControlPresupuestoLongitud;
    private javax.swing.JLabel lblControlTitulo;
    private javax.swing.JLabel lblControlTituloLongitud;
    private javax.swing.JLabel lblcontrolAnio;
    private javax.swing.JLabel lblcontrolAnioLongitud;
    private javax.swing.JLabel lblcontrolIDLongitud;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtPresupuesto;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    private final File ficheroObjetos=new File("peliculas.dat");

//    private RAF claseFicheroAleatorio;
    
    private JTextField[] campos;
}
