package modelos;
// Generated 21-feb-2014 23:39:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ExArticulos generated by hbm2java
 */
public class ExArticulos  implements java.io.Serializable {


     private int idarticulo;
     private String descrArtic;
     private BigDecimal precioUnitario;
     private Boolean eliminado;
     private Set exVentases = new HashSet(0);

    public ExArticulos() {
    }

	
    public ExArticulos(int idarticulo, BigDecimal precioUnitario) {
        this.idarticulo = idarticulo;
        this.precioUnitario = precioUnitario;
    }
    public ExArticulos(int idarticulo, String descrArtic, BigDecimal precioUnitario, Boolean eliminado, Set exVentases) {
       this.idarticulo = idarticulo;
       this.descrArtic = descrArtic;
       this.precioUnitario = precioUnitario;
       this.eliminado = eliminado;
       this.exVentases = exVentases;
    }
   
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public String getDescrArtic() {
        return this.descrArtic;
    }
    
    public void setDescrArtic(String descrArtic) {
        this.descrArtic = descrArtic;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Boolean getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set getExVentases() {
        return this.exVentases;
    }
    
    public void setExVentases(Set exVentases) {
        this.exVentases = exVentases;
    }




}


